### ISSUE TITLE
Error: Invalid syntax: 0a.h.

### ISSUE THREAD

**Issue by kleeb** [ionic-team/ionic-app-scripts#1008]
app-scripts version 1.3.7

happens during uglifying release build, only on UNIX machines (Ubuntu)

```
[13:58:00]  uglifyjs started ... 
[13:58:01]  ionic-app-script task: "build" 
[13:58:01]  Error: Invalid syntax: 0a.h in www/build/main.js at line 26191, col 
            119, pos 1000563 
Error: Invalid syntax: 0a.h in www/build/main.js at line 26191, col 119, pos 1000563
    at new BuildError (node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at taskReject (node_modules/@ionic/app-scripts/dist/worker-process.js:36:22)
    at node_modules/@ionic/app-scripts/dist/worker-process.js:14:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by kleeb** [comment]
I guess its related to this one https://github.com/rollup/rollup/issues/1275

**Comment by kleeb** [comment]
Upgrading to

```
    "angularfire2": "4.0.0-rc.1",
    "firebase": "4.1.2",
```

helps
