### ISSUE TITLE
Module not found: Error: Can't resolve 'reduce'

### ISSUE THREAD

**Issue by lweb20** [ionic-team/ionic-app-scripts#1061]
#### Short description of the problem:
Build failed in production build only.

#### What behavior are you expecting?

**Steps to reproduce:**
1. ionic-app-scripts build --prod

```
> ionic-app-scripts build --prod

[15:20:05]  ionic-app-scripts 1.3.8
[15:20:05]  build prod started ...
[15:20:05]  clean started ...
[15:20:05]  clean finished in less than 1 ms
[15:20:05]  copy started ...
[15:20:05]  ngc started ...
[15:20:17]  ngc finished in 11.92 s
[15:20:17]  preprocess started ...
[15:20:17]  deeplinks started ...
[15:20:18]  deeplinks finished in 875 ms
[15:20:18]  optimization started ...
[15:20:18]  copy finished in 13.14 s
[15:20:35]  ionic-app-script task: "build"
[15:20:35]  Error: ./~/@ionic/cloud/~/superagent/lib/client.js Module not found: Error: Can't resolve 'reduce' in
            'D:\projects\project-name\node_modules\@ionic\cloud\node_modules\superagent\lib' resolve 'reduce' in
            'D:\projects\project-name\node_modules\@ionic\cloud\node_modules\superagent\lib' Parsed request is a module
            using description file:
            D:\projects\project-name\node_modules\@ionic\cloud\node_modules\superagent\package.json (relative path:
            ./lib) aliased from description file
            D:\projects\project-name\node_modules\@ionic\cloud\node_modules\superagent\package.json with mapping 'reduce'
            to 'reduce-component' Parsed request is a module using description file:
            D:\projects\project-name\node_modules\@ionic\cloud\node_modules\superagent\package.json (relative path: .)
            after using description file:
            D:\projects\project-name\node_modules\@ionic\cloud\node_modules\superagent\package.json (relative path: .)
            resolve as module D:\projects\project-name\node_modules\@ionic\node_modules doesn't exist or is not a
            directory D:\projects\project-name\node_modules\node_modules doesn't exist or is not a directory
            D:\projects\node_modules doesn't exist or is not a directory D:\node_modules doesn't exist or is not a
            directory D:\projects\project-name\node_modules\@ionic\cloud\node_modules\node_modules doesn't exist or is
            not a directory D:\projects\project-name\node_modules\@ionic\cloud\node_modules\superagent\node_modules
            doesn't exist or is not a directory looking for modules in
            D:\projects\project-name\node_modules\@ionic\cloud\node_modules using description file:
            D:\projects\project-name\node_modules\@ionic\cloud\package.json (relative path: ./node_modules) Field
            'browser' doesn't contain a valid alias configuration after using description file:
            D:\projects\project-name\node_modules\@ionic\cloud\package.json (relative path: ./node_modules) using
            description file: D:\projects\project-name\node_modules\@ionic\cloud\package.json (relative path:
            ./node_modules/reduce-component) as directory
            D:\projects\project-name\node_modules\@ionic\cloud\node_modules\reduce-component doesn't exist no extension
            Field 'browser' doesn't contain a valid alias configuration
            D:\projects\project-name\node_modules\@ionic\cloud\node_modules\reduce-component doesn't exist .js Field
            'browser' doesn't contain a valid alias configuration
            D:\projects\project-name\node_modules\@ionic\cloud\node_modules\reduce-component.js doesn't exist .ts Field
            'browser' doesn't contain a valid alias configuration
            D:\projects\project-name\node_modules\@ionic\cloud\node_modules\reduce-component.ts doesn't exist looking for
            modules in D:\projects\project-name\node_modules using description file: D:\projects\project-name\package.json
            (relative path: ./node_modules) Field 'browser' doesn't contain a valid alias configuration after using
            description file: D:\projects\project-name\package.json (relative path: ./node_modules) using description
            file: D:\projects\project-name\package.json (relative path: ./node_modules/reduce-component) as directory
            D:\projects\project-name\node_modules\reduce-component doesn't exist no extension Field 'browser' doesn't
            contain a valid alias configuration D:\projects\project-name\node_modules\reduce-component doesn't exist .js
            Field 'browser' doesn't contain a valid alias configuration
            D:\projects\project-name\node_modules\reduce-component.js doesn't exist .ts Field 'browser' doesn't contain a
            valid alias configuration D:\projects\project-name\node_modules\reduce-component.ts doesn't exist
            [D:\projects\project-name\node_modules\@ionic\node_modules]
            [D:\projects\project-name\node_modules\node_modules] [D:\projects\node_modules] [D:\node_modules]
            [D:\projects\project-name\node_modules\@ionic\cloud\node_modules\node_modules]
            [D:\projects\project-name\node_modules\@ionic\cloud\node_modules\superagent\node_modules]
            [D:\projects\project-name\node_modules\@ionic\cloud\node_modules\reduce-component]
            [D:\projects\project-name\node_modules\@ionic\cloud\node_modules\reduce-component]
            [D:\projects\project-name\node_modules\@ionic\cloud\node_modules\reduce-component.js]
            [D:\projects\project-name\node_modules\@ionic\cloud\node_modules\reduce-component.ts]
            [D:\projects\project-name\node_modules\reduce-component]
            [D:\projects\project-name\node_modules\reduce-component]
            [D:\projects\project-name\node_modules\reduce-component.js]
            [D:\projects\project-name\node_modules\reduce-component.ts] @ ./~/@ionic/cloud/~/superagent/lib/client.js
            6:13-30 @ ./~/@ionic/cloud/dist/es5/client.js @ ./src/app/app.module.ngfactory.js @ ./src/app/main.ts
Error: ./~/@ionic/cloud/~/superagent/lib/client.js
Module not found: Error: Can't resolve 'reduce' in 'D:\projects\project-name\node_modules\@ionic\cloud\node_modules\superagent\lib'
resolve 'reduce' in 'D:\projects\project-name\node_modules\@ionic\cloud\node_modules\superagent\lib'
  Parsed request is a module
  using description file: D:\projects\project-name\node_modules\@ionic\cloud\node_modules\superagent\package.json (relative path: ./lib)
    aliased from description file D:\projects\project-name\node_modules\@ionic\cloud\node_modules\superagent\package.json with mapping 'reduce' to 'reduce-component'
      Parsed request is a module
      using description file: D:\projects\project-name\node_modules\@ionic\cloud\node_modules\superagent\package.json (relative path: .)
      after using description file: D:\projects\project-name\node_modules\@ionic\cloud\node_modules\superagent\package.json (relative path: .)
        resolve as module
          D:\projects\project-name\node_modules\@ionic\node_modules doesn't exist or is not a directory
          D:\projects\project-name\node_modules\node_modules doesn't exist or is not a directory
          D:\projects\node_modules doesn't exist or is not a directory
          D:\node_modules doesn't exist or is not a directory
          D:\projects\project-name\node_modules\@ionic\cloud\node_modules\node_modules doesn't exist or is not a directory
          D:\projects\project-name\node_modules\@ionic\cloud\node_modules\superagent\node_modules doesn't exist or is not a directory
          looking for modules in D:\projects\project-name\node_modules\@ionic\cloud\node_modules
            using description file: D:\projects\project-name\node_modules\@ionic\cloud\package.json (relative path: ./node_modules)
              Field 'browser' doesn't contain a valid alias configuration
            after using description file: D:\projects\project-name\node_modules\@ionic\cloud\package.json (relative path: ./node_modules)
              using description file: D:\projects\project-name\node_modules\@ionic\cloud\package.json (relative path: ./node_modules/reduce-component)
                as directory
                  D:\projects\project-name\node_modules\@ionic\cloud\node_modules\reduce-component doesn't exist
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  D:\projects\project-name\node_modules\@ionic\cloud\node_modules\reduce-component doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  D:\projects\project-name\node_modules\@ionic\cloud\node_modules\reduce-component.js doesn't exist
                .ts
                  Field 'browser' doesn't contain a valid alias configuration
                  D:\projects\project-name\node_modules\@ionic\cloud\node_modules\reduce-component.ts doesn't exist
          looking for modules in D:\projects\project-name\node_modules
            using description file: D:\projects\project-name\package.json (relative path: ./node_modules)
              Field 'browser' doesn't contain a valid alias configuration
            after using description file: D:\projects\project-name\package.json (relative path: ./node_modules)
              using description file: D:\projects\project-name\package.json (relative path: ./node_modules/reduce-component)
                as directory
                  D:\projects\project-name\node_modules\reduce-component doesn't exist
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  D:\projects\project-name\node_modules\reduce-component doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  D:\projects\project-name\node_modules\reduce-component.js doesn't exist
                .ts
                  Field 'browser' doesn't contain a valid alias configuration
                  D:\projects\project-name\node_modules\reduce-component.ts doesn't exist
[D:\projects\project-name\node_modules\@ionic\node_modules]
[D:\projects\project-name\node_modules\node_modules]
[D:\projects\node_modules]
[D:\node_modules]
[D:\projects\project-name\node_modules\@ionic\cloud\node_modules\node_modules]
[D:\projects\project-name\node_modules\@ionic\cloud\node_modules\superagent\node_modules]
[D:\projects\project-name\node_modules\@ionic\cloud\node_modules\reduce-component]
[D:\projects\project-name\node_modules\@ionic\cloud\node_modules\reduce-component]
[D:\projects\project-name\node_modules\@ionic\cloud\node_modules\reduce-component.js]
[D:\projects\project-name\node_modules\@ionic\cloud\node_modules\reduce-component.ts]
[D:\projects\project-name\node_modules\reduce-component]
[D:\projects\project-name\node_modules\reduce-component]
[D:\projects\project-name\node_modules\reduce-component.js]
[D:\projects\project-name\node_modules\reduce-component.ts]
 @ ./~/@ionic/cloud/~/superagent/lib/client.js 6:13-30
 @ ./~/@ionic/cloud/dist/es5/client.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts
    at new BuildError (D:\projects\project-name\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at D:\projects\project-name\node_modules\@ionic\app-scripts\dist\preprocess.js:18:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project-name@3.0.0 build-prd: `ionic-app-scripts build --prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the project-name@3.0.0 build-prd script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alan\AppData\Roaming\npm-cache\_logs\2017-06-26T20_20_35_912Z-debug.log
```

**Which @ionic/app-scripts version are you using?**
1.3.8

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
npm -v: 5.0.4 (fail in 5.0.3 too)
node -v: v8.1.2 (fail in 6.11.0 too)

**Comment by danielsogl** [comment]
Looks like a problem with the @ionic/cloud package. Did this error appear after updating to app-scripts 1.3.8?

**Comment by lweb20** [comment]
I tested in npm v4 and works fine. I think that is something related with npm version 5.

**Comment by jgw96** [comment]
Hello @lweb20 , this is in fact an `npm 5` issue. `npm 5.x` has been very buggy with installing dependencies of dependencies. I just updated to 5.3.0 and this seems to have fixed some of these issues. Because this is an npm issue and not an Ionic issue I am going to close this for now. Thanks!
