### ISSUE TITLE
Unable to cordova build android --prod

### ISSUE THREAD

**Issue by ivanovvitaly** [ionic-team/ionic-app-scripts#1070]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
When I run ionic cordova build android --prod it fails with error

#### What behavior are you expecting?
Should create optimized for production android package 

**Steps to reproduce:**
1. ionic cordova build android --prod

```
ionic cordova build android --prod
Running app-scripts build: --prod --iscordovaserve --externalIpRequired --nobrowser

[16:05:17]  build prod started ...
[16:05:17]  clean started ...
[16:05:17]  clean finished in 2 ms
[16:05:17]  copy started ...
[16:05:17]  ngc started ...
[16:05:27]  ngc finished in 9.72 s
[16:05:27]  preprocess started ...
[16:05:27]  deeplinks started ...
[WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova). Your plugins may be out of
       date.
Error: The RegExp to find the DeepLinkConfigToken did not return valid data
```

**Which @ionic/app-scripts version are you using?**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.0
    ios-sim    : not installed
    npm        : 5.0.4
```

**Comment by tgensol** [comment]
Which version of angular do you use ?

**Comment by ivanovvitaly** [comment]
@tgensol 4.1.3

**Comment by tgensol** [comment]
I only have this issue if I use angular 4.2.X, with 4.1.3 and the last ionic 1.3.5 I do not have it... :/

**Comment by RafaelKr** [comment]
Same issue for me.

**Comment by janpio** [comment]
Can you all run `npm run ionic:build --prod` please? 
Does it give you the same output? 
If so, can you run the same command with `--verbose` added at the end please and post the output (and your `ionic info` again plus your current `package.json` of the project) here?

**Comment by RafaelKr** [comment]
error-output for `npm run ionic:build --prod --verbose`
```
[15:19:06]  deeplinks started ... 
[15:19:06]  ionic-app-script task: "build" 
[15:19:06]  Error: The RegExp to find the DeepLinkConfigToken did not return valid data 
Error: The RegExp to find the DeepLinkConfigToken did not return valid data
    at new BuildError (/home/rafael/Coding/Office/Advifyer/App/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /home/rafael/Coding/Office/Advifyer/App/node_modules/@ionic/app-scripts/dist/preprocess.js:18:21
    at <anonymous>
npm verb lifecycle @advifyer/app@~ionic:build: unsafe-perm in lifecycle true
npm verb lifecycle @advifyer/app@~ionic:build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/rafael/Coding/Office/Advifyer/App/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/rafael/bin:/usr/local/java/jdk1.8.0_102/bin:/home/rafael/android-sdk-linux/tools:/home/rafael/android-sdk-linux/platform-tools:/home/rafael/android-sdk-linux/tools:/home/rafael/android-sdk-linux/platform-tools:/home/rafael/android-sdk-linux/tools:/home/rafael/android-sdk-linux/platform-tools
npm verb lifecycle @advifyer/app@~ionic:build: CWD: /home/rafael/Coding/Office/Advifyer/App
npm info lifecycle @advifyer/app@~ionic:build: Failed to exec ionic:build script
npm verb stack Error: @advifyer/app@ ionic:build: `ionic-app-scripts build`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at EventEmitter.emit (events.js:213:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at ChildProcess.emit (events.js:213:7)
npm verb stack     at maybeClose (internal/child_process.js:887:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
npm verb pkgid @advifyer/app@
npm verb cwd /home/rafael/Coding/Office/Advifyer/App
npm verb Linux 4.10.0-21-generic
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:build" "--prod" "--verbose"
npm verb node v8.0.0
npm verb npm  v5.0.4
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @advifyer/app@ ionic:build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @advifyer/app@ ionic:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
```

**Comment by bleuscyther** [comment]
same only happens with angular 4.2.x :  
global packages:

    @ionic/cli-plugin-proxy : 1.3.2
    @ionic/cli-utils        : 1.5.0
    Cordova CLI             : 7.0.1
    Ionic CLI               : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.1
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 windows 5.0.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.2.0

**Comment by DedSec49** [comment]
This problems gets solved when we use angular 4.1.x.  
But what if I want to use 4.2.x only.  Is cordova lagging behind with the angular updates and there is no fix for this.
I need angular 4.2 as there are new animation functions.

**Comment by janpio** [comment]
Ionic is not ready for Angular 4.2 yet. 

See the current base package.json for a ionic-angular 3.5 project:
https://github.com/ionic-team/ionic2-app-base/blob/9b39d206f2bc894931116161519a2eed2284fadf/package.json
Angular is pinned to 4.1.3 for a good reason.

**Comment by DedSec49** [comment]
So when is ionic going to update to support angular 4.2. As in A4.2 there are new animations features that I really want to use for my app.

**Comment by janpio** [comment]
No idea. Create an issue at https://github.com/ionic-team/ionic/issues - maybe someone else can already tell you how to make it work with angular 4.2

**Comment by danielsogl** [comment]
I created a PR for this last month :D https://github.com/ionic-team/ionic/pull/12000
Still waiting for the merge

**Comment by AghaAliAbbasKhan** [comment]
Just downgrade angular to 4.1.3 and remove ^ symbol before 4.1.3 in package.json and issue will be resolved

**Comment by cooldp007** [comment]
My ionic info :-1: 

cli packages: (D:\ej\ejohri-spare\node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.1.1
    Node              : v6.10.3
    npm               : 5.4.2
    OS                : Windows 7

Misc:

    backend : legacy


My Angular Version:

@angular/cli: 1.4.3
node: 6.10.3
os: win32 x64
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/compiler-cli: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/cli: 1.4.3
typescript: 2.5.2


Error:-

D:\ej\ejohri-spare>ionic cordova build android --prod
[INFO] Running app-scripts build: --prod --platform android --target cordova

[15:02:34]  build prod started ...
[15:02:34]  clean started ...
[15:02:34]  clean finished in 2 ms
[15:02:34]  copy started ...
[15:02:34]  ngc started ...
[15:02:51]  ngc finished in 16.87 s
[15:02:51]  preprocess started ...
[15:02:51]  deeplinks started ...
Error: The RegExp to find the DeepLinkConfigToken did not return valid data
    at BuildError.Error (native)
    at new BuildError (D:\ej\ejohri-spare\node_modules\@ionic\app-scripts\dist\u
til\errors.js:16:28)
    at D:\ej\ejohri-spare\node_modules\@ionic\app-scripts\dist\preprocess.js:18:
21


Please resolve my bugs

**Comment by janpio** [comment]
@cooldp007 Please don't post the same problem in multiple places. The community forum is enough: https://forum.ionicframework.com/t/how-to-solve-app-script-issue/107429/5

**Comment by cooldp007** [comment]
okay 
sorry:-

**Comment by raxim1** [comment]
It's related to the @ionic/app-scripts (3.0.1) it's mostly under devDependency - , what you need to upgrade also. ionic-angular 3.8.0 requires 4.4.4

new need to add vendor.js before main.js in the index.html

Unfortunatelly @ionic-native-mocks/splash-screen and @ionic-native-mocks/status-bar requires angular 3.2.1, so it's not in sync with the latest product

I have a problem with webworker, which requires independent js file.
Webpack CommonsChunkPlugin works with appscript 2.0.4, after initiating som JsonPMainTemplatePlugin fix, but appscript 3.0.1 simply does not work with it.

If you don't use webworker, i was able to build for 'prod'

**Comment by carloshs92** [comment]
Did someone could fix this error?
