### ISSUE TITLE
Cannot find module "./data-table-collection" on ionic serve

### ISSUE THREAD

**Issue by iget-master** [ionic-team/ionic-app-scripts#1071]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Using `ionic serve` on my project, sometimes (looks randomically) after it rebuild, it simply dont find a file included on a component. The file is `data-table-collection.d.ts`, it's an interface that's used in another files.

It outputs the following error: 

`Uncaught (in promise): Error: Cannot find module "./data-table-collection" Error: Cannot find module "./data-table-collection" at Object.365 (http://localhost:8100/build/0.main.js:54:7) at __webpack_require__ (http://localhost:8100/build/main.js:50:30) at Object.366 (http://localhost:8100/build/0.main.js:211:80) at __webpack_require__ (http://localhost:8100/build/main.js:50:30) at Object.364 (http://localhost:8100/build/0.main.js:13:92) at __webpack_require__ (http://localhost:8100/build/main.js:50:30) at http://localhost:8100/build/main.js:80244:10 at t.invoke (http://localhost:8100/build/polyfills.js:3:8971) at Object.onInvoke (http://localhost:8100/build/main.js:4510:37) at t.invoke (http://localhost:8100/build/polyfills.js:3:8911)`

I don't need to say that my code is right, since it works sometimes.
There's no variables that may affect it. 

This component (that imports that failing interface) is being used inside an IonicPage, lazy loaded.
The file exists, and it's open on my IDE (phpstorm).

When it fails, only killing `ionic serve` and restarting it solves the problem. This is occurring with constantly here and it's blocking my work.

I'm using it over Ubuntu 16.04, everything up-to-date.

#### What behavior are you expecting?

It should just work!

**Steps to reproduce:**
1. `ionic serve`
2. Work a while with everything running ok
3. After some file change (not necessarily the component or the interface), it just fails with the error.

```
// The interface
export interface DataTableCollection {
  models: Array<any>,
  pagination: {
    count: number,
    total: number,
    current_page: number,
    per_page: number,
    total_pages: number,
  }
}
```

```
// The import on the compoent
import {DataTableCollection} from "./data-table-collection";
```

**Which @ionic/app-scripts version are you using?**

global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.11.0
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

I've tried to increase inotify limit, not sure if this is the problem, but increased to a huge limit (50M) without success.

Sometimes if I open the file on IDE, change it and save, the code compiles fine and run.
Sometimes it only fix by restarting ionic serve.

**Comment by iget-master** [comment]
The issue looks similar to #690.

**Comment by tallybh** [comment]
you are a life saver
