### ISSUE TITLE
Nightly Build 1.3.12-201707060514 (webpack3) +angular2-moment shows errors in production builds

### ISSUE THREAD

**Issue by dmastag** [ionic-team/ionic-app-scripts#1081]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Using nightly build 1.3.12-201707060514 (webpack3) +angular2-moment shows errors in production builds

#### What behavior are you expecting?
Production Build should 

**Steps to reproduce:**
1. Create new Ionic Project from Blank Template
2. add angular2-moment ([Link to Repo](https://github.com/urish/angular2-moment))
3. run `npm uninstall @ionic/app-scripts `
4. run `npm install @ionic/app-scripts@nightly --save-dev`
5. run `npm run build --prod`

**Which @ionic/app-scripts version are you using?**
1.3.12-201707060514

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

I made a Git Repo for the problem https://github.com/dmastag/ionic-moment--error

I am using the nightly build as per @danbucholtz suggestion on https://github.com/ionic-team/ionic-app-scripts/issues/971#issuecomment-313303419

But I am afraid that if this goes to production that a lot of people who are using angular2-moment will have a problem

**Comment by dmastag** [comment]
Updated to Nightly 1.3.12-201707071538

**Comment by dmastag** [comment]
Here is the latest Error Console

D:\GM Work Box\playground\ionic20170706-moment>npm run build --prod

> ionic20170706-moment@0.0.1 build D:\GM Work Box\playground\ionic20170706-moment
> ionic-app-scripts build

[00:29:27]  ionic-app-scripts 1.3.12-201707071538
[00:29:27]  build prod started ...
[00:29:27]  clean started ...
[00:29:27]  clean finished in 4 ms
[00:29:27]  copy started ...
[00:29:27]  ngc started ...
[00:29:32]  ngc finished in 4.96 s
[00:29:32]  preprocess started ...
[00:29:32]  deeplinks started ...
[00:29:32]  deeplinks finished in 35 ms
[00:29:32]  optimization started ...
[00:29:32]  copy finished in 5.21 s
[00:29:39]  optimization finished in 7.21 s
[00:29:39]  preprocess finished in 7.34 s
[00:29:39]  webpack started ...
[00:30:46]  webpack finished in 67.03 s
[00:30:46]  sass started ...
[00:30:46]  uglifyjs started ...
[00:30:46]  ionic-app-script task: "build"
[00:30:46]  Error: ENOENT: no such file or directory, scandir 'D:\GM Work
            Box\playground\ionic20170706-moment\node_modules\moment\locale \^'
Error: ENOENT: no such file or directory, scandir 'D:\GM Work Box\playground\ionic20170706-moment\node_modules\moment\locale \^'
    at Object.fs.readdirSync (fs.js:909:18)
    at getSiblingSassFiles (D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:155:23)
    at addComponentSassFiles (D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:132:24)
    at D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:127:9
    at Array.forEach (native)
    at getComponentSassFiles (D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:126:26)
    at generateSassData (D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:111:30)
    at D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:71:13
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic20170706-moment@0.0.1 build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic20170706-moment@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\julia\AppData\Roaming\npm-cache\_logs\2017-07-07T17_30_46_682Z-debug.log

**Comment by dmastag** [comment]
Tried it out on a Mac with the same result:

```
Julians-Mac-2:projects julianalimin$ git clone https://github.com/dmastag/ionic-moment--error
Cloning into 'ionic-moment--error'...
remote: Counting objects: 101, done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 101 (delta 12), reused 101 (delta 12), pack-reused 0
Receiving objects: 100% (101/101), 1.63 MiB | 793.00 KiB/s, done.
Resolving deltas: 100% (12/12), done.
Julians-Mac-2:projects julianalimin$ cd ionic-moment--error/
Julians-Mac-2:ionic-moment--error julianalimin$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
Julians-Mac-2:ionic-moment--error julianalimin$ npm install
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-Yi4y6CSItJJ5EUpPns9F581rulU= integrity checksum failed when using sha1: wanted sha1-Yi4y6CSItJJ5EUpPns9F581rulU= but got sha512-q4spe4KTfsAS1SUHLO0wz8Qiyf1+vMIAgpRYioFYDMNqKfHQbg+AVDH3i4fvpl71/P1L0dBl+fQi+P37UYf0ew==. (6052 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-gxlF4pNltHCqhySwqzbI+JWdEPs= integrity checksum failed when using sha1: wanted sha1-gxlF4pNltHCqhySwqzbI+JWdEPs= but got sha512-mmLbumEYMi5nXReB9js3WGsB8UE6cDBWyIO62Z4DNx6GbRhDxHNjA1MlzSpJ2S2KM1wyiPRA0d19uHWYYvMHjA==. (1992 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> node-sass@4.5.3 install /Users/julianalimin/projects/ionic-moment--error/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/julianalimin/.npm/node-sass/4.5.3/darwin-x64-57_binding.node

> node-sass@4.5.3 postinstall /Users/julianalimin/projects/ionic-moment--error/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/julianalimin/projects/ionic-moment--error/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/julianalimin/projects/ionic-moment--error/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

added 725 packages in 20.952s
Julians-Mac-2:ionic-moment--error julianalimin$ npm run build --prod

> ionic20170706-moment@0.0.1 build /Users/julianalimin/projects/ionic-moment--error
> ionic-app-scripts build

[01:54:04]  ionic-app-scripts 1.3.12-201707071538 
[01:54:04]  build prod started ... 
[01:54:04]  clean started ... 
[01:54:04]  clean finished in 1 ms 
[01:54:04]  copy started ... 
[01:54:04]  ngc started ... 
[01:54:10]  ngc finished in 5.27 s 
[01:54:10]  preprocess started ... 
[01:54:10]  deeplinks started ... 
[01:54:10]  deeplinks finished in 26 ms 
[01:54:10]  optimization started ... 
[01:54:10]  copy finished in 5.57 s 
[01:54:18]  optimization finished in 8.49 s 
[01:54:18]  preprocess finished in 8.67 s 
[01:54:18]  webpack started ... 
[01:55:39]  webpack finished in 81.21 s 
[01:55:39]  sass started ... 
[01:55:39]  uglifyjs started ... 
[01:55:39]  ionic-app-script task: "build" 
[01:55:39]  Error: ENOENT: no such file or directory, scandir 
            '/Users/julianalimin/projects/ionic-moment--error/node_modules/moment/locale /^\.\' 
Error: ENOENT: no such file or directory, scandir '/Users/julianalimin/projects/ionic-moment--error/node_modules/moment/locale /^\.\'
    at Object.fs.readdirSync (fs.js:909:18)
    at getSiblingSassFiles (/Users/julianalimin/projects/ionic-moment--error/node_modules/@ionic/app-scripts/dist/sass.js:155:23)
    at addComponentSassFiles (/Users/julianalimin/projects/ionic-moment--error/node_modules/@ionic/app-scripts/dist/sass.js:132:24)
    at /Users/julianalimin/projects/ionic-moment--error/node_modules/@ionic/app-scripts/dist/sass.js:127:9
    at Array.forEach (native)
    at getComponentSassFiles (/Users/julianalimin/projects/ionic-moment--error/node_modules/@ionic/app-scripts/dist/sass.js:126:26)
    at generateSassData (/Users/julianalimin/projects/ionic-moment--error/node_modules/@ionic/app-scripts/dist/sass.js:111:30)
    at /Users/julianalimin/projects/ionic-moment--error/node_modules/@ionic/app-scripts/dist/sass.js:71:13
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic20170706-moment@0.0.1 build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic20170706-moment@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/julianalimin/.npm/_logs/2017-07-07T18_55_40_085Z-debug.log
Julians-Mac-2:ionic-moment--error julianalimin$ (node:876) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
(node:876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by dmastag** [comment]
Opened an issue at angular2-moment and they suggest that this has something to do with ionic/app-scripts.

https://github.com/urish/angular2-moment/issues/152#issuecomment-313711031

**Comment by danbucholtz** [comment]
Can you try the latest nightly? I think this is fixed.

Thanks,
Dan

**Comment by dmastag** [comment]
Just tried it out and its working.
Updating the repo and am closing this now.

**Comment by ztecharoberts** [comment]
looks good to me as well.
