### ISSUE TITLE
Problems restoring the wkwebview on Windows 10

### ISSUE THREAD

**Issue by pjc2007** [ionic-team/ionic-app-scripts#1089]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
I have been having problems adding the Windows platform to my project. Seems to be some sort of conflict with the wkwebview I am using for iOS. I have a forum post relating to this [here](https://forum.ionicframework.com/t/adding-windows-platform-is-trying-to-add-cordova-plugin-wkwebview-engine-and-causing-an-error/97286/2). So I thought I'd just try doing the same with a new blank project.

Using my Mac, I have created a new Ionic project, using the blank template, and then added the iOS platform, and also the wkwebview as described [here](https://github.com/ionic-team/cordova-plugin-wkwebview-engine). I need the wkwebview  is my real project to fix some issues I was having on iOS. All works fine and I can run this on the Mac.

Now I clone the project over to my Windows machines, as I want to add the Windows platform as I was trying to do for my real application. I didn't even get up to being able to install the windows platform, I got an error while installing the npm packages...

`      npm install
      ✖ Running command - failed!
      [ERROR] An error occurred while running npm install (exit code 1):

        npm ERR! Error while executing:
        npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t
        https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git
        npm ERR!
        npm ERR! fatal: Unable to find remote helper for 'https'
        npm ERR!
        npm ERR! exited with error code: 128

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\Peter\AppData\Roaming\npm-cache\_logs\2017-07-09T02_25_31_814Z-debug.log`

The last bit of the above log where the error occurs has the following..

```
228 silly fetchPackageMetaData error for cordova-plugin-wkwebview-engine@git+https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git Error while executing:
228 silly fetchPackageMetaData C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git
228 silly fetchPackageMetaData
228 silly fetchPackageMetaData fatal: Unable to find remote helper for 'https'
228 silly fetchPackageMetaData
228 silly fetchPackageMetaData exited with error code: 128
229 http fetch GET 200 https://registry.npmjs.org/cordova-ios/-/cordova-ios-4.4.0.tgz 7246ms
230 silly pacote https://registry.npmjs.org/cordova-ios/-/cordova-ios-4.4.0.tgz extracted in 7423ms
231 silly addBundled read tarball
232 silly cleanup remove extracted module
233 verbose stack Error: exited with error code: 128
233 verbose stack     at ChildProcess.onexit (C:\Users\Peter\AppData\Roaming\npm\node_modules\npm\node_modules\mississippi\node_modules\end-of-stream\index.js:39:36)
233 verbose stack     at emitTwo (events.js:106:13)
233 verbose stack     at ChildProcess.emit (events.js:191:7)
233 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
234 verbose cwd D:\dev\ionic\blank2
235 verbose Windows_NT 10.0.14393
236 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Peter\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
237 verbose node v6.11.0
238 verbose npm  v5.1.0
239 error Error while executing:
239 error C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git
239 error
239 error fatal: Unable to find remote helper for 'https'
239 error
239 error exited with error code: 128
240 verbose exit [ 1, true ]
```
Should we even be installing the wkwebview on Windows since this is for iOS only? Not sure what to do to get around this.

#### What behavior are you expecting?
To be able to restore npm modules and add the Windows platform on a Windows 10 machine

**Steps to reproduce:**
1. on a Mac, create a new blank project
2. Add the wkwebview as per instructions [here](https://github.com/ionic-team/cordova-plugin-wkwebview-engine)
3. Once verifies works on on Mac, transfer project onto a Windows machine
4. Run `npm install` (I can't get past this step)
5. Once the above is restored, run `ionic cordova platform add windows`

**Which @ionic/app-scripts version are you using?**
Installed the latest when had problems,,
"@ionic/app-scripts": "2.0.0",

Ionic info on Windows machine
```
global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 2.0.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.11.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.1.0
```

**Comment by pjc2007** [comment]
I can get around this by removing the  `wkwebview ` from `package.config` and `config.xml`, but would be good to not have to do this.

**Comment by janpio** [comment]
The error message you are getting is of `git`. Everything else is just followup problems. Maybe try installing a newer version?
