### ISSUE TITLE
Prod build failing on sass step

### ISSUE THREAD

**Issue by jbarbede** [ionic-team/ionic-app-scripts#1107]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
I am using the last version of ionic/app-scripts (2.0.1) and the build fails on the sass step when using the --prod flag. I have the following error:

`TypeError: Cannot read property 'forEach' of undefined 
TypeError: Cannot read property 'forEach' of undefined
    at generateSassData (.../node_modules/@ionic/app-scripts/dist/sass.js:98:24)
    at .../node_modules/@ionic/app-scripts/dist/sass.js:71:13`

#### What behavior are you expecting?
The sass step should suceed with the --prod flag like it does when building in dev.

**Which @ionic/app-scripts version are you using?**

2.0.1

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

It looks like sass task doesn't have access to the list of module files.
Webpack task limits access to those module files there: 
https://github.com/ionic-team/ionic-app-scripts/blob/master/src/webpack.ts#L96

**Comment by jbarbede** [comment]
hey @danbucholtz, I saw the change in 2.0.2 that fixes `Cannot read property 'forEach' of undefined at generateSassData`, exactly my error above, but now with --prod I simply don't have styles correctly built.

I don't know why but ionic styles actually are missing when I build with --prod.

**Comment by jbarbede** [comment]
Closing the ticket, it was related to my customized optimization config file not up to date with last changes.
