### ISSUE TITLE
Ionic Build Cordova android 

### ISSUE THREAD

**Issue by MuhammadTahir92** [ionic-team/ionic-app-scripts#1146]
× Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova build android (exit code 1):

        (truncated) ... rg.gradle.wrapper.Install$1.call(Install.java:47)
        at
        org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        ... 3 more
        Caused by: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1880)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1825)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:116)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.MeteredStream.read(MeteredStream.java:134)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at
        sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3375)
        at
        sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3368)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:63)
        ... 7 more
        Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
        at sun.security.ssl.InputRecord.read(InputRecord.java:532)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        ... 14 more
        Error: cmd: Command failed with exit code 1 Error output:
        Exception in thread "main" java.lang.RuntimeException: javax.net.ssl.SSLException:
        Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException:
        Connection reset
        at
        org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
        at org.gradle.wrapper.Install.createDist(Install.java:47)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
        Caused by: javax.net.ssl.SSLException: Connection has been shutdown:
        javax.net.ssl.SSLException: java.net.SocketException: Connection reset
        at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1551)
        at sun.security.ssl.AppInputStream.available(AppInputStream.java:60)
        at java.io.BufferedInputStream.available(BufferedInputStream.java:410)
        at sun.net.www.MeteredStream.available(MeteredStream.java:170)
        at sun.net.www.http.KeepAliveStream.close(KeepAliveStream.java:85)
        at java.io.FilterInputStream.close(FilterInputStream.java:181)
        at
        sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.close(HttpURLConnection.java:3448)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:74)
        at org.gradle.wrapper.Download.download(Download.java:45)
        at org.gradle.wrapper.Install$1.call(Install.java:60)
        at org.gradle.wrapper.Install$1.call(Install.java:47)
        at
        org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        ... 3 more
        Caused by: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1880)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1825)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:116)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.MeteredStream.read(MeteredStream.java:134)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at
        sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3375)
        at
        sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3368)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:63)
        ... 7 more
        Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
        at sun.security.ssl.InputRecord.read(InputRecord.java:532)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        ... 14 more

**Comment by shareef1989** [comment]
+1
Same issue

**Comment by rajmani1995** [comment]
I think this error is coming is due to this url `https://services.gradle.org/distributions/gradle-3.3-all.zip`
when I check head of this url using `curl --head https://services.gradle.org/distributions/gradle-3.3-all.zip`
I got this result
```
HTTP/1.1 301 Moved Permanently
Date: Wed, 02 Aug 2017 15:28:40 GMT
Connection: keep-alive
Cache-Control: max-age=3600
Expires: Wed, 02 Aug 2017 16:28:40 GMT
Location: https://downloads.gradle.org/distributions/gradle-3.3-all.zip
Server: cloudflare-nginx
CF-RAY: 3882117c2daa2fbd-MAA
```
Java is not able to download due to HTTP_RESPONSE_CODE=301
I tried to replace `https://services.gradle.org/distributions/gradle-3.3-all.zip` with
`https://downloads.gradle.org/distributions/gradle-3.3-all.zip` but it didn't work
please help!
