### ISSUE TITLE
generators: TypeError: Cannot read property 'constant' of undefined

### ISSUE THREAD

**Issue by Janesamurai** [ionic-team/ionic-app-scripts#1149]
#### Short description of the problem:
When running `ionic generate tabs` in an ionic **sidemenu** project, I get:

> TypeError: Cannot read property 'constants' of undefined

Tabs are not created and when running `ionic serve` the webpage opens, but without any tabs.

#### What behavior are you expecting? 

**Steps to reproduce:**
1. Run `ionic start sidemenu`.
2. Run `ionic generate tabs` inside project folder.
3. Follow cmd prompts
4. Get described error

```
C:\Users\Username\myapp>ionic generate tabs --verbose
[DEBUG] Loading global plugin @ionic/cli-plugin-proxy
[DEBUG] Throwing PLUGIN_NOT_INSTALLED for global @ionic/cli-plugin-proxy
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
? What should the name be? mytabs
? How many tabs? 1
? Name of this tab: one
[DEBUG] !!! ERROR ENCOUNTERED !!!
TypeError: Cannot read property 'constants' of undefined
[DEBUG] TypeError: Cannot read property 'constants' of undefined
        at Object.processTabsRequest (C:\Users\Username\myapp\node_modules\@ionic\app-scripts\dist\generators.js:28:46)
        at Object.<anonymous> (C:\Users\Username\myapp\node_modules\@ionic\cli-plugin-ionic-angular\dist\generate.js:58:34)
        at Generator.next (<anonymous>)
        at fulfilled (C:\Users\Username\myapp\node_modules\@ionic\cli-plugin-ionic-angular\dist\generate.js:4:58)
        at <anonymous>
```

**Which @ionic/app-scripts version are you using?**
My `ionic info` is
```
C:\Users\Username\MyProject>ionic info

global packages:

    @ionic/cli-utils : 1.5.0
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.1.0
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v8.2.1
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.3.0
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

When I installed the latest version of app-scripts I got a few `WARN` messages which may be relevant:

```
C:\Users\Username\MyProject>npm install @ionic/app-scripts@latest --save-dev
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @ionic/app-scripts@2.1.0
added 114 packages and updated 1 package in 65.289s
```
This issue seems to be related to the closed issue:
[https://github.com/ionic-team/ionic-cli/issues/2519](url)

In following what was requested of the poster in the issue linked to, I provide the contents of app.module.ts:

```
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
import { ListPage } from '../pages/list/list';

import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

@NgModule({
  declarations: [
    MyApp,
    HomePage,
    ListPage
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    ListPage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}
```

**Comment by Janesamurai** [comment]
After the update to Ionic CLI 3.6.0 and @ionic/cli-plugin-ionic-angular, I am no longer experiencing this issue!
Yay!
