### ISSUE TITLE
[2.1.0] Throwing error after ionig generate

### ISSUE THREAD

**Issue by UncertaintyP** [ionic-team/ionic-app-scripts#1150]
#### Short description of the problem:
The command `ionic g` throws an error, nevertheless its doing its job before.

#### What behavior are you expecting?
No error

**Steps to reproduce:**
1. ionic g
2. component
3. enter name

```
? What would you like to generate: component
? What should the name be? ClubCard
[OK] Generated a component named ClubCard!
TypeError: Cannot read property 'initializer' of undefined
    at Object.appendNgModuleExports (/home/heisenberg/code/cap/node_modules/@ionic/app-scripts/dist/util/typescript-utils.js:238:33)
    at /home/heisenberg/code/cap/node_modules/@ionic/app-scripts/dist/generators/util.js:246:58
```

```
global packages:

    @ionic/cli-plugin-proxy : 1.3.2
    @ionic/cli-utils        : 1.5.0
    Cordova CLI             : 7.0.1 
    Ionic CLI               : 3.5.0

local packages:

    @ionic/app-scripts              : 2.1.0
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v6.10.0
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.3.0
```

**Comment by SearchingSoul** [comment]
Had the same issue after upgrading @ionic/app-scripts to 2.1.0, moved back to 2.0.2 & was here to check if anyone else had a similar problem.

**Comment by UncertaintyP** [comment]
Solved in current version. Thanks guys <3

**Comment by UncertaintyP** [comment]
close Thx guys :)
