### ISSUE TITLE
Strange behaviors using `--aot` and `--prod`

### ISSUE THREAD

**Issue by hadrien-toma** [ionic-team/ionic-app-scripts#1156]
#### Short description of the problem:
I try to use a component that works perfectly (except for the `caseC` that is Ionic specific) in an Angular project based on `@angular/cli` version `1.2.6`, using `ng serve`, `ng serve --aot` and `ng serve --prod`. In Ionic, some things work with `--aot` but not with `--prod` and the Ionic specific use case doesn't work at all, in a strange way.

#### What behavior are you expecting?
1. I would like to have the `caseB` (not Ionic specific) working as it works in the Angular project.
1. Of course, I also would like to have the `caseC` working.

**Steps to reproduce:**
1. Start a `blank` Ionic project
```bash
ionic start otf blank
cd otf
```
2. Create the following:
* `src/pages/` and `src/pages/page/` directories and remove the `src/pages/home/` one.
* `src/pages/page/page.html` file with content:
```html
<ion-header>
	<ion-navbar>
		<ion-title>page</ion-title>
	</ion-navbar>
</ion-header>
<ion-content padding>
	<div #viewContainerRef></div>
</ion-content>
```
* `src/pages/page/page.module.ts` file with content:
```ts
import { NgModule, Compiler } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { Page } from "./page";
import { JitCompilerFactory } from "@angular/compiler";

export function createJitCompiler() {
	return (new JitCompilerFactory([{ useDebug: false, useJit: true }]).createCompiler());
}

@NgModule({
	declarations: [Page],
	imports: [IonicPageModule.forChild(Page)],
	providers: [{ provide: Compiler, useFactory: createJitCompiler }],
	exports: [Page]
})
export class PageModule { }
```
* `src/pages/page/page.ts` file with content:
```ts
import { Component, ViewContainerRef, Compiler, Injector, NgModuleRef, ViewChild, NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { IonicPage, IonicModule } from "ionic-angular";

@IonicPage()
@Component({
	selector: 'page',
	templateUrl: 'page.html',
})
export class Page {
	@ViewChild('viewContainerRef', { read: ViewContainerRef }) viewContainerRef: ViewContainerRef;
	constructor(
		private compiler: Compiler,
		private injector: Injector,
		private ngModuleRef: NgModuleRef<any>
	) { }
	ionViewDidLoad(){
		const caseA = {
			template: '<span>{{name}}</span>',
			getImports: (component) => []
		};
		const caseB = {
			template: '<span *ngIf="true">{{name}}</span>',
			getImports: (component) => [CommonModule]
		};
		const caseC = {
			template: '<ion-item *ngIf="true">{{name}}</ion-item>',
			getImports: (component) => [CommonModule, IonicModule.forRoot(component)]
		};
		const { template, getImports } = caseA;
		//const { template, getImports } = caseB;
		//const { template, getImports } = caseC;

		const component = Component({ template })(class { });
		const ngModule = NgModule({ declarations: [component], imports: getImports(component) })(class { });
		this.compiler.compileModuleAndAllComponentsAsync(ngModule).then((factories) => {
			const factory = factories.componentFactories[0];
			const componentRef = factory.create(this.injector, [], null, this.ngModuleRef);
			componentRef.instance.name = 'Hello World!';
			this.viewContainerRef.insert(componentRef.hostView);
		});
	}
}
```
3. Update the application module, replacing
* `src/app/app.component.ts` file's content by:
```ts
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import { Page } from "../pages/page/page";

@Component({
	templateUrl: 'app.html'
})
export class MyApp{
	rootPage: any = Page
	constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen){
		platform.ready().then(() => {
			statusBar.styleDefault();
			splashScreen.hide();
		});
	}
}
```
* `src/app/app.module.ts` file's content by:
```ts
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';
import { MyApp } from './app.component';
import { PageModule } from "../pages/page/page.module";

@NgModule({
	declarations: [
		MyApp
	],
	imports: [
		BrowserModule,
		IonicModule.forRoot(MyApp),
		PageModule
	],
	bootstrap: [IonicApp],
	entryComponents: [
		MyApp
	],
	providers: [
		StatusBar,
		SplashScreen,
		{ provide: ErrorHandler, useClass: IonicErrorHandler }
	]
})
export class AppModule { }
```
4. Execute the following commands, similar results should be given:
* For `caseA `: HTML templating
  * `ionic cordova run android`:
    * :smiley:: Works as expected.
    * `deviceready event fired after 6145 ms`
  * `ionic cordova run android --aot`:
    * :smiley:: Works as expected.
    * `deviceready event fired after 492 ms`
  * `ionic cordova run android --prod`:
    * :smiley:: Works as expected.
    * `deviceready event fired after 940 ms`
* For `caseB` : Angular common modules integration
  * Comment the `caseA` line in `src/pages/page/page.ts` and uncomment the `caseB` line.
  * `ionic cordova run android`:
    * :smiley:: Works as expected.
    * `deviceready event fired after 5954 ms`
  * `ionic cordova run android --aot`:
    * :smiley:: Works as expected.
    * `deviceready event fired after 571 ms` (:heart_eyes:)
  * `ionic cordova run android --prod`:
    * :cry:: Trigger the error detailed in a next section.
    * `deviceready event fired after 802 ms`
* For `caseC` : Ionic common modules integration
  * Comment the `caseB` line in `src/pages/page/page.ts` and uncomment the `caseC` line
  * `ionic cordova run android`:
    * :confused:: No errors but the created component is at least, *not visible*. If you confirm that what I do is correct but what I am facing is a bug in this case, I will explore deeper this behaviour if needed.
    * `deviceready event fired after 6707 ms`
  * `ionic cordova run android --aot`:
    * :confused:: Same behaviour as before : no errors but the created component is at least, *not visible*. If you confirm that what I do is correct but what I am facing is a bug in this case, I will explore deeper this behaviour if needed.
    * `deviceready event fired after 6025 ms`
  * `ionic cordova run android --prod`:
    * :cry:: Trigger the error detailed in a next section.
    * `deviceready event fired after 908 ms`

**Which @ionic/app-scripts version are you using?**
`ionic info`:
```bash
cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0 (/home/hadrien-toma/otf/node_modules/@ionic/cli-plugin-cordova)
    @ionic/cli-plugin-ionic-angular : 1.4.0 (/home/hadrien-toma/otf/node_modules/@ionic/cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (/home/hadrien-toma/otf/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (/home/hadrien-toma/otf/node_modules/ionic)

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.1
    OS                : Linux 3.19
    npm               : 3.10.10 
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Error description
```bash
ERROR Error: Unexpected value 'function (){}' imported by the module 'function (){}'. Please add a @NgModule annotation.
    at Error (native)
    at _ (file:///android_asset/www/build/vendor.js:1:459821)
    at file:///android_asset/www/build/vendor.js:1:651225
    at Array.forEach (native)
    at t.getNgModuleMetadata (file:///android_asset/www/build/vendor.js:1:650930)
    at t._loadModules (file:///android_asset/www/build/vendor.js:1:755962)
    at t._compileModuleAndAllComponents (file:///android_asset/www/build/vendor.js:1:755726)
    at t.compileModuleAndAllComponentsAsync (file:///android_asset/www/build/vendor.js:1:755063)
    at t.ionViewDidLoad (file:///android_asset/www/build/main.js:1:520)
    at t._lifecycle
```

**Comment by DrMabuse23** [comment]
same here

**Comment by hadrien-toma** [comment]
My solution was to switch over Angular + Cordova and to forget Ionic :disappointed: ...

**Comment by jaufgang** [comment]
@hadrien-toma, how are you finding working with Angular & Cordova without Ionic?  Are you using `ionic-native` for the cordova-plugins-wrapped-as-angular-services, and just leaving out `ionic-angular`?

**Comment by hadrien-toma** [comment]
With Angular + Cordova only the code mentioned just works as it is. Concerning native APIs, you can use whatever Cordova plugins you want or Native Script or other native framework. But keep in mind that with that solution, Ionic is not used (you can try to use Ionic scripts without the rest of the framework but I didn't try that).

**Comment by liuwings** [comment]
my solution was to remove "@IonicPage()" and module file
