### ISSUE TITLE
Ionic serve dont serve the app on the browser

### ISSUE THREAD

**Issue by leonardocoutinho** [ionic-team/ionic-app-scripts#1167]
Hi,
Ionic serve gives an error when in try to serve my app on the browser:
'TypeError: Cannot read property 'launchBrowser' of undefined'

Ionic Info
``` cli packages: (/home/leonardo/3ionicprojects/cdm_admin/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.11.2
    OS   : Linux 4.4
    npm  : 3.10.10 
```

When i run the command 'ionic serve --verbose':

```
leonardo@coutinho-pc:~/3ionicprojects/cdm_admin$ ionic serve --verbose
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: '/home/leonardo/3ionicprojects/cdm_admin', local: true, binPath:
        '/usr/local/lib/node_modules/ionic/bin/ionic', libPath:
        '/home/leonardo/3ionicprojects/cdm_admin/node_modules/ionic/dist/index.js' }
[DEBUG] Loading local plugin @ionic/cli-plugin-proxy
[DEBUG] Throwing PLUGIN_NOT_INSTALLED for local @ionic/cli-plugin-proxy
[DEBUG] Loading local plugin @ionic/cli-plugin-cordova
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
[DEBUG] Daemon found (pid: 3977)
[DEBUG] Getting plugin info for ionic
[DEBUG] Checking for latest plugin version of ionic@latest.
[DEBUG] Getting plugin info for @ionic/cli-plugin-cordova
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-cordova@latest.
[DEBUG] Getting plugin info for @ionic/cli-plugin-ionic-angular
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-ionic-angular@latest.
[INFO] Starting app-scripts server: --log-level debug --port 8100 --p 8100 --livereload-port 35729 --r 35729 --address
       localhost - Ctrl+C to cancel
TypeError: Cannot read property 'launchBrowser' of undefined
[DEBUG] TypeError: Cannot read property 'launchBrowser' of undefined
        at onReady (/home/leonardo/3ionicprojects/cdm_admin/node_modules/@ionic/app-scripts/dist/serve.js:70:15)
        at /home/leonardo/3ionicprojects/cdm_admin/node_modules/@ionic/app-scripts/dist/serve.js:63:13
        at process._tickCallback (internal/process/next_tick.js:109:7)
```

I reinstall the @ionic/app-scripts, and i see a new file in the root folder of my project without a format, the name of the file is:  =5.0.0 and the content inside of the file is:
``` 
cdm_admin@0.0.1 /home/leonardo/3ionicprojects/cdm_admin
├─┬ @ionic/app-scripts@2.1.3 invalid
│ └─┬ node-sass@4.5.3
│   └─┬ request@2.81.0
│     └─┬ har-validator@4.2.1
│       └── ajv@4.11.8 
└── ajv@5.2.2 
```

**Comment by santiq** [comment]
Same issue here!

```
$ ionic info

cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0
    @ionic/cli-plugin-ionic-angular : 1.4.0
    @ionic/cli-plugin-proxy         : 1.4.1
    @ionic/cli-utils                : 1.6.0 
    ionic (Ionic CLI)               : 3.6.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.5.3

System:

    Node : v6.11.0
    OS   : macOS Sierra
    npm  : 3.10.10 



```

**Comment by leonardocoutinho** [comment]
Hello @santiq seems the error is in the new version of ionic the version 3.6.0.
After several hours trying i found the solution, i have to downgrade to version 3.5.0, i delete the node_modules/ folder, npm install again and the problem is resolved.

**Comment by sachingarg05** [comment]
For me this happens only when localhost is not defined in OS /etc/hosts file. (Like if you are editing it for ad-blocking or debug-redirects etc). It will help if there is a more informative error message when this happens.

**Comment by rachidsakara** [comment]
If ionic serve doesn’t serve your app on the browser, go ahead and type the **following command**: 
`npm run ionic:serve`
and this command will definitely do the trick.
