### ISSUE TITLE
Ionic prod build failing when adding jszip library

### ISSUE THREAD

**Issue by slaviki** [ionic-team/ionic-app-scripts#1177]
#### Short description of the problem:
When I add jszip library ro Ionic project build failing with error

#### What behavior are you expecting?
Successfull build

**Steps to reproduce:**
1. Create new ionic project with Ionic CLI
2. npm i jszip --save
3. Add following lines to app.module.ts:

`import JSZip from 'jszip';`
`new JSZip();`

4. Run ionic build --prod
5. It fails with error:
[10:38:41]  webpack started ...
[10:38:44]  ionic-app-script task: "build"
[10:38:44]  Error: ./node_modules/jszip/lib/index.js Module build failed: RangeError: Maximum call stack size exceeded
            at checkGrammarForDisallowedTrailingComma
            (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:46692:56) at checkGrammarTypeArguments
            (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:46806:20) at checkCallExpression
            (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:39834:13) at checkExpressionWorker
            (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:41305:28) at checkExpression
            (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:41257:42) at checkExpressionCached
            (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:41138:38) at
            C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:40197:32 at traverse
            (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:7261:28) at visitEachNode
            (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:14785:30) at Object.forEachChild
            (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:14957:24) @ ./src/app/app.module.ts
            17:0-26 @ ./src/app/app.module.ngfactory.ts @ ./src/app/main.ts
Error: ./node_modules/jszip/lib/index.js
Module build failed: RangeError: Maximum call stack size exceeded
    at checkGrammarForDisallowedTrailingComma (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:46692:56)
    at checkGrammarTypeArguments (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:46806:20)
    at checkCallExpression (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:39834:13)
    at checkExpressionWorker (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:41305:28)
    at checkExpression (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:41257:42)
    at checkExpressionCached (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:41138:38)
    at C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:40197:32
    at traverse (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:7261:28)
    at visitEachNode (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:14785:30)
    at Object.forEachChild (C:\Development\zzz\T545942\node_modules\typescript\lib\typescript.js:14957:24)
 @ ./src/app/app.module.ts 17:0-26
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts
    at BuildError.Error (native)
    at new BuildError (C:\Development\zzz\T545942\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (C:\Development\zzz\T545942\node_modules\@ionic\app-scripts\dist\webpack.js:119:28)
    at emitRecords.err (C:\Development\zzz\T545942\node_modules\webpack\lib\Compiler.js:269:13)
    at Compiler.emitRecords (C:\Development\zzz\T545942\node_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (C:\Development\zzz\T545942\node_modules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (C:\Development\zzz\T545942\node_modules\webpack\lib\Compiler.js:368:12)
    at next (C:\Development\zzz\T545942\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (C:\Development\zzz\T545942\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (C:\Development\zzz\T545942\node_modules\tapable\lib\Tapable.js:222:13)

**Which @ionic/app-scripts version are you using?**
I tried with 1.3.7 and 2.1.3

**Comment by Jun711** [comment]
@slaviki  what are 1.3.7 and 2.1.3 version numbers for?
And, have you tried checkout this [thread](https://github.com/ionic-team/ionic-app-scripts/issues/996) ?
