### ISSUE TITLE
--prod build still fails with external config files.

### ISSUE THREAD

**Issue by roylkng** [ionic-team/ionic-app-scripts#1186]
webpack.config.ts
`var path = require('path');
var useDefaultConfig = require('@ionic/app-scripts/config/webpack.config.js');

module.exports = function () {
    useDefaultConfig.resolve.alias = {
        "@app/config": path.resolve('./src/config/config.' + process.env.IONIC_ENV + '.ts')
    };

    return useDefaultConfig;
}`

changed package.json
` "config": {
    "ionic_webpack": "./src/config/webpack.config.js"
  },`

even tried with both of these `
    "ionic_optimization": "./src/config/optimization.config.js",
    "ionic_dependency_tree": "./src/config/optimization.config.js",`
.
works fine on 
ionic serve --dev
ionic serve --prod
ionic build --dev
npm run build

does not work for
ionic build --prod
npm run build --prod

error:
`[19:09:11]  ionic-app-script task: "build" 
[19:09:11]  Error: ./src/channel/channel.service.js Module not found: Error: Can't resolve '@app/config' in 
            '/Users/anvista-3/Desktop/rajan/dibot/ui/src/channel' resolve '@app/config' in 
            '/Users/anvista-3/Desktop/rajan/dibot/ui/src/channel' Parsed request is a module using description file: 
            /Users/anvista-3/Desktop/rajan/dibot/ui/package.json (relative path: ./src/channel) Field 'browser' doesn't 
            contain a valid alias configuration after using description file: 
            /Users/anvista-3/Desktop/rajan/dibot/ui/package.json (relative path: ./src/channel) resolve as module 
            /Users/anvista-3/Desktop/rajan/dibot/ui/src/channel/node_modules doesn't exist or is not a directory 
            /Users/anvista-3/Desktop/rajan/dibot/ui/src/node_modules doesn't exist or is not a directory 
            /Users/anvista-3/Desktop/rajan/node_modules doesn't exist or is not a directory 
            /Users/anvista-3/Desktop/node_modules doesn't exist or is not a directory /Users/anvista-3/node_modules 
            doesn't exist or is not a directory /Users/node_modules doesn't exist or is not a directory /node_modules 
            doesn't exist or is not a directory looking for modules in 
            /Users/anvista-3/Desktop/rajan/dibot/ui/node_modules using description file: 
            /Users/anvista-3/Desktop/rajan/dibot/ui/package.json (relative path: ./node_modules) Field 'browser' doesn't 
            contain a valid alias configuration after using description file: 
            /Users/anvista-3/Desktop/rajan/dibot/ui/package.json (relative path: ./node_modules) using description file: 
            /Users/anvista-3/Desktop/rajan/dibot/ui/package.json (relative path: ./node_modules/@app/config) no 
            extension Field 'browser' doesn't contain a valid alias configuration 
            /Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@app/config doesn't exist .js Field 'browser' doesn't 
            contain a valid alias configuration /Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@app/config.js 
            doesn't exist .ts Field 'browser' doesn't contain a valid alias configuration 
            /Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@app/config.ts doesn't exist as directory 
            /Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@app/config doesn't exist looking for modules in 
            /Users/anvista-3/Desktop/rajan/dibot/node_modules using description file: 
            /Users/anvista-3/Desktop/rajan/dibot/package.json (relative path: ./node_modules) Field 'browser' doesn't 
            contain a valid alias configuration after using description file: 
            /Users/anvista-3/Desktop/rajan/dibot/package.json (relative path: ./node_modules) using description file: 
            /Users/anvista-3/Desktop/rajan/dibot/package.json (relative path: ./node_modules/@app/config) no extension 
            Field 'browser' doesn't contain a valid alias configuration 
            /Users/anvista-3/Desktop/rajan/dibot/node_modules/@app/config doesn't exist .js Field 'browser' doesn't 
            contain a valid alias configuration /Users/anvista-3/Desktop/rajan/dibot/node_modules/@app/config.js doesn't 
            exist .ts Field 'browser' doesn't contain a valid alias configuration 
            /Users/anvista-3/Desktop/rajan/dibot/node_modules/@app/config.ts doesn't exist as directory 
            /Users/anvista-3/Desktop/rajan/dibot/node_modules/@app/config doesn't exist 
            [/Users/anvista-3/Desktop/rajan/dibot/ui/src/channel/node_modules] 
            [/Users/anvista-3/Desktop/rajan/dibot/ui/src/node_modules] [/Users/anvista-3/Desktop/rajan/node_modules] 
            [/Users/anvista-3/Desktop/node_modules] [/Users/anvista-3/node_modules] [/Users/node_modules] 
            [/node_modules] [/Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@app/config] 
            [/Users/anvista-3/Desktop/rajan/dibot/node_modules/@app/config] 
            [/Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@app/config.js] 
            [/Users/anvista-3/Desktop/rajan/dibot/node_modules/@app/config.js] 
            [/Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@app/config.ts] 
            [/Users/anvista-3/Desktop/rajan/dibot/node_modules/@app/config.ts] 
            [/Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@app/config] 
            [/Users/anvista-3/Desktop/rajan/dibot/node_modules/@app/config] @ ./src/channel/channel.service.js 13:0-34 @ 
            ./src/insightfeed/insightfeed.page.js @ ./src/app/app.module.js @ ./src/app/app.module.ngfactory.js @ 
            ./src/app/main.ts 
Error: ./src/channel/channel.service.js
Module not found: Error: Can't resolve '@app/config' in '/Users/anvista-3/Desktop/rajan/dibot/ui/src/channel'
resolve '@app/config' in '/Users/anvista-3/Desktop/rajan/dibot/ui/src/channel'
  Parsed request is a module
  using description file: /Users/anvista-3/Desktop/rajan/dibot/ui/package.json (relative path: ./src/channel)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/anvista-3/Desktop/rajan/dibot/ui/package.json (relative path: ./src/channel)
    resolve as module
      /Users/anvista-3/Desktop/rajan/dibot/ui/src/channel/node_modules doesn't exist or is not a directory
      /Users/anvista-3/Desktop/rajan/dibot/ui/src/node_modules doesn't exist or is not a directory
      /Users/anvista-3/Desktop/rajan/node_modules doesn't exist or is not a directory
      /Users/anvista-3/Desktop/node_modules doesn't exist or is not a directory
      /Users/anvista-3/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/anvista-3/Desktop/rajan/dibot/ui/node_modules
        using description file: /Users/anvista-3/Desktop/rajan/dibot/ui/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/anvista-3/Desktop/rajan/dibot/ui/package.json (relative path: ./node_modules)
          using description file: /Users/anvista-3/Desktop/rajan/dibot/ui/package.json (relative path: ./node_modules/@app/config)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@app/config doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@app/config.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@app/config.ts doesn't exist
            as directory
              /Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@app/config doesn't exist
      looking for modules in /Users/anvista-3/Desktop/rajan/dibot/node_modules
        using description file: /Users/anvista-3/Desktop/rajan/dibot/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/anvista-3/Desktop/rajan/dibot/package.json (relative path: ./node_modules)
          using description file: /Users/anvista-3/Desktop/rajan/dibot/package.json (relative path: ./node_modules/@app/config)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/anvista-3/Desktop/rajan/dibot/node_modules/@app/config doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/anvista-3/Desktop/rajan/dibot/node_modules/@app/config.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/anvista-3/Desktop/rajan/dibot/node_modules/@app/config.ts doesn't exist
            as directory
              /Users/anvista-3/Desktop/rajan/dibot/node_modules/@app/config doesn't exist
[/Users/anvista-3/Desktop/rajan/dibot/ui/src/channel/node_modules]
[/Users/anvista-3/Desktop/rajan/dibot/ui/src/node_modules]
[/Users/anvista-3/Desktop/rajan/node_modules]
[/Users/anvista-3/Desktop/node_modules]
[/Users/anvista-3/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@app/config]
[/Users/anvista-3/Desktop/rajan/dibot/node_modules/@app/config]
[/Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@app/config.js]
[/Users/anvista-3/Desktop/rajan/dibot/node_modules/@app/config.js]
[/Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@app/config.ts]
[/Users/anvista-3/Desktop/rajan/dibot/node_modules/@app/config.ts]
[/Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@app/config]
[/Users/anvista-3/Desktop/rajan/dibot/node_modules/@app/config]
 @ ./src/channel/channel.service.js 13:0-34
 @ ./src/insightfeed/insightfeed.page.js
 @ ./src/app/app.module.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts
    at new BuildError (/Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /Users/anvista-3/Desktop/rajan/dibot/ui/node_modules/@ionic/app-scripts/dist/preprocess.js:18:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)`

**Comment by lostdev** [comment]
I am having the same issue.

**Comment by franbueno** [comment]
Same error over here

**Comment by lejoe** [comment]
I have the same problem.
It looks like in the early stages of the build, the variables are not aliased yet.

If you add tsconfig.json like on this page it should work:
https://artyomsokolov.com/how-to-use-different-environment-variables-for-production-and-development-with-ionic-3/

The downside is that it works only if you have one "prod-like" build.
Meaning you can't have a pre-prod env that build like for prod because it's going to take the variables from the real prod file because of this tsconfig.

**Comment by kinglionsoft** [comment]
I am having the same issue.
