### ISSUE TITLE
Failed to transpile program error with ionic cordova build

### ISSUE THREAD

**Issue by Jun711** [ionic-team/ionic-app-scripts#1193]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Error: Failed to transpile program 
Got the above error when I run ionic cordova build ios

**Steps to reproduce:**
1. ionic cordova build ios

```
// tsconfig.json
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "declaration": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "lib": [
            "dom",
            "es2015"
        ],
        "module": "es2015",
        "moduleResolution": "node",
        "sourceMap": true,
        "target": "es5",
        "types": [
            "node"
        ]
    },
    "include": [
        "src/**/*.ts"
    ],
    "exclude": [
      "./node_modules",
        "src/test.ts",
        "src/**/*.spec.ts"
    ],
    "compileOnSave": false,
    "atom": {
        "rewriteTsconfig": false
    }
}
```

**Which @ionic/app-scripts version are you using?**
app-scripts 2.1.4

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by tundak** [comment]
any update ? i got same issue https://forum.ionicframework.com/t/error-failed-to-transpile-program/103408

**Comment by francoro** [comment]
+1

**Comment by polfernandez** [comment]
+1

**Comment by harishintimetec** [comment]
+1

**Comment by carryall** [comment]
+1

**Comment by alherrera42** [comment]
+1

**Comment by marioshtika** [comment]
If you created a new provider and there was an error in the provider class (ex. a missing bracket)
This was in my case.

**Comment by erperejildo** [comment]
I updated and got this error as well. Was working perfectly before

**Comment by LeiwenL** [comment]
+1

**Comment by PivitParkour94** [comment]
+1

**Comment by PivitParkour94** [comment]
Actually, 3 words. `ionic doctor check` <3

**Comment by pmvcaqr** [comment]
@PivitParkour94 Thank you, you save my day

**Comment by PivitParkour94** [comment]
Glad I could help man! My issue was having the default bundle ID in the config.xml still. Would be cool if the error message was somewhat obvious. Oh well. Maybe one day ;)

**Comment by mauricewipf** [comment]
I ran `$ Ionic doctor check`, fixed the issues and now there are 0 issues. But I still get this error in the Build Log on Ionic Dashboard:

```
Error: Failed to transpile program
    at new BuildError (/usr/src/app/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /usr/src/app/node_modules/@ionic/app-scripts/dist/transpile.js:159:20
    at Promise ()
    at transpileWorker (/usr/src/app/node_modules/@ionic/app-scripts/dist/transpile.js:107:12)
    at Object.transpile (/usr/src/app/node_modules/@ionic/app-scripts/dist/transpile.js:64:12)
    at /usr/src/app/node_modules/@ionic/app-scripts/dist/build.js:109:82
    at 
npm info lifecycle NoMeat@0.0.1~build: Failed to exec build script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MyApp@0.0.1 build: `ionic-app-scripts build`
npm ERR! Exit status 1
```

**Comment by domezchoc** [comment]
+1

**Comment by Perolanegra** [comment]
> I ran $ Ionic doctor check, fixed the issues and now there are 0 issues. But I still get this error in the Build Log on Ionic Dashboard:

Error: Failed to transpile program
    at new BuildError (/usr/src/app/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /usr/src/app/node_modules/@ionic/app-scripts/dist/transpile.js:159:20
    at Promise ()
    at transpileWorker (/usr/src/app/node_modules/@ionic/app-scripts/dist/transpile.js:107:12)
    at Object.transpile (/usr/src/app/node_modules/@ionic/app-scripts/dist/transpile.js:64:12)
    at /usr/src/app/node_modules/@ionic/app-scripts/dist/build.js:109:82
    at 
npm info lifecycle NoMeat@0.0.1~build: Failed to exec build script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MyApp@0.0.1 build: `ionic-app-scripts build`
npm ERR! Exit status 1


Samething here...

**Comment by moscoso** [comment]
Error: Failed to transpile program
at new BuildError (/usr/src/app/node_modules//dist/util/errors.js:16:28)
at /usr/src/app/node_modules//dist/transpile.js:159:20
at Promise ()
at transpileWorker (/usr/src/app/node_modules//dist/transpile.js:107:12)
at Object.transpile (/usr/src/app/node_modules//dist/transpile.js:64:12)
at /usr/src/app/node_modules//dist/build.js:109:82
at
npm info lifecycle NoMeat@0.0.1~build: Failed to exec build script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MyApp@0.0.1 build: ionic-app-scripts build
npm ERR! Exit status 1

Same error as above

**Comment by rayhaanq** [comment]
same issue

**Comment by roccobar** [comment]
same issue for me...

No one?

**Comment by alaingoodarzi** [comment]
same issue

**Comment by jhonatasblue** [comment]
It just happened to me.

`Error: Failed to transpile program
    at new BuildError (/Users/jhonatasrosendo/dev/blue_mobile_app/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /Users/jhonatasrosendo/dev/blue_mobile_app/node_modules/@ionic/app-scripts/dist/transpile.js:159:20
    at new Promise (<anonymous>)
    at transpileWorker (/Users/jhonatasrosendo/dev/blue_mobile_app/node_modules/@ionic/app-scripts/dist/transpile.js:107:12)
    at Object.transpile (/Users/jhonatasrosendo/dev/blue_mobile_app/node_modules/@ionic/app-scripts/dist/transpile.js:64:12)
    at /Users/jhonatasrosendo/dev/blue_mobile_app/node_modules/@ionic/app-scripts/dist/build.js:109:82
    at <anonymous>`


`ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v8.10.0
    npm               : 5.6.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Users/jhonatasrosendo/Library/Android/sdk

Misc:

    backend : legacy`

**Comment by lkrubner** [comment]
Same here. If I try: 
 
    ionic cordova prepare

I get: 

    typescript: src/components/push-notification/push-notification.ts, line: 61 

and:

     Error: Failed to transpile program
        at BuildError.Error (native)


    ionic info
    [WARN] Detected locally installed Ionic CLI, but it's too old--using global CLI.
    
    cli packages: (/usr/local/lib/node_modules)
    
        @ionic/cli-utils  : 1.19.2
        ionic (Ionic CLI) : 3.20.0
    
    global packages:
    
        cordova (Cordova CLI) : 7.1.0 
    
    local packages:
    
        @ionic/app-scripts : 2.1.4
        Cordova Platforms  : android 6.3.0 browser 5.0.3 ios 4.5.4
        Ionic Framework    : ionic-angular 3.6.0
    
    System:
    
        ios-deploy : 1.9.2 
        Node       : v6.5.0
        npm        : 3.10.3 
        OS         : macOS High Sierra
        Xcode      : Xcode 9.2 Build version 9C40b 
    
    Environment Variables:
    
        ANDROID_HOME : not set
    
    Misc:
    
        backend : pro

If I run:

    ionic doctor check

It fixed some issues, but also left me with: 

    Fixed 2 issues!
    3 issues need to be fixed manually.

I assume some of those manual issues include:

       A major update is available for Ionic Native (3.12.1 => 4.6.0). To fix, take the following step(s):
       
            1) Visit https://github.com/ionic-team/ionic-native/releases, looking for breaking changes
            2) Update each @ionic-native/ package. For example, npm i --save -E @ionic-native/core@4.6.0
            3) Update your app according to the breaking changes, if any
       
       Ignore this issue with: ionic doctor ignore ionic-native-major-update-available

**Comment by arcvpatel** [comment]
I am getting this error as well. Here's my ionic info

`cli packages: (/root/jenkins/workspace/Smartpatient/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v9.10.1
    npm  : 5.6.0
    OS   : Linux 2.6

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro`

This works just fine on my local mac machine. However, when I try to run this on CentOS server, that's when I see the error.
Any help on this would be highly appreciated.

**Comment by UrbanSwati** [comment]
Fixed this by installing [yarn](https://yarnpkg.com/)  then inside the project folder I ran `yarn` which is like `npm install` but somehow better (https://www.sitepoint.com/yarn-vs-npm/)

**Comment by shrewmus** [comment]
Fixed this with find and remove any imports from the '@angular/compiler-cli'

**Comment by ggobea** [comment]
+1

**Comment by germanramos** [comment]
Same error. Nothing described above works for me.

**Comment by Jcortesjara** [comment]
+1

**Comment by arangos** [comment]
+1

**Comment by jorgster** [comment]
+1

**Comment by Jcortesjara** [comment]
hi everyone
I downgrade my angular version to 5.0.0 and fixed that. I thing typescript have conflicts version with angular 6+.

my versions.
------------------------------------
Angular CLI: 1.5.6
Node: 6.11.1
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router


@angular-devkit/architect: 0.6.8
@angular-devkit/build-angular: 0.6.8
@angular-devkit/build-optimizer: 0.6.8
@angular-devkit/core: 0.6.8
@ngtools/webpack: 6.0.8
typescript: 2.9.2
webpack: 4.17.1

**Comment by jorgster** [comment]
That makes a lot of sense.

**Comment by harveyelsisura** [comment]
Same here, still having a problem

**Comment by jorgster** [comment]
@harveyelsisura.

I was able to fix it on my end. What does your --verbose say?

**Comment by nimeso** [comment]
+1 This is driving me nuts

**Comment by dinesh-krish** [comment]
Issue Fixed By following
After adding platform  use following command --> cordova clean

**Comment by prog-24** [comment]
Changing my typescript version to 2.9.2 seems to have solved my problem.

**Comment by 2diegoduque** [comment]
+1

**Comment by daldantas** [comment]
Same issue.
