### ISSUE TITLE
Ionic serve & build both stops mid way before building the app

### ISSUE THREAD

**Issue by ibrahimAboelsuod** [ionic-team/ionic-app-scripts#1211]
#### Short description of the problem:
Ionic serve & build both stops mid way before building or serving the app.
This behavior happens if you have 2 components under the same folder if both has html templates files.
`
[INFO] Starting app-scripts server: --address 0.0.0.0 --port 8100 --livereload-port 35729 - Ctrl+C to cancel
[19:56:35]  watch started ...
[19:56:35]  build dev started ...
[19:56:35]  Proxy added:/ => http://10.100.101.8:8083/
[19:56:35]  clean started ...
[19:56:35]  clean finished in 4 ms
[19:56:35]  copy started ...
[19:56:35]  transpile started ...
[19:56:39]  transpile finished in 4.17 s
[19:56:39]  preprocess started ...
[19:56:39]  deeplinks started ...
[19:56:39]  deeplinks finished in 237 ms
[19:56:39]  preprocess finished in 239 ms
[19:56:39]  webpack started ...
[19:56:40]  copy finished in 4.99 s
`

#### What behavior are you expecting?
The app to build/ get served in localhost. OR the cli to throw an error.

**Steps to reproduce:**
1. Create a CustomSelectComponent .
2. In the .ts file add another one so you are left with:
`
import ...;
@Component({
  selector: 'custom-select',
  templateUrl: 'custom-select.html',
  host: {
    '[id]': "'custom-select'"
  }
})
export class CustomSelectComponent {
  constructor() {}
}

@Component({
  templateUrl:'custom-select-list.html'
})
export class CustomSelectListSubComponent {
  constructor() {}
}
`
3. Create both .html files.
4. Run `ionic serve` or `ionic build`

**Which @ionic/app-scripts version are you using?**
#### Ionic info:
`
cli packages: (E:\Ionic\workspace\mb\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.3.1
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.2
    npm               : 5.4.0
    OS                : Windows 10
`

**Other information:** 
1- If you have my "weird" structure you can overcome this issue by embedding the template in the .ts file like wise:
`@Component({
  template:  `<!--HTML code-->`
})`

2- I think this issue is also related to how the components are named but I am not sure.

3- The reason I had this structure is because I was creating a custom select (drop down list) so I had an HTML part where the user clicks to open the list and another to display the list as a popover. I could have done it all in css and ts or kept the popover concept and separated the components but that seemed cleaner and more logical to me (because one of them is not a component, but together they make one).

#### npm run ionic:build --verbose Output:
`
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\iaboelsuod\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'run',
npm verb cli   'ionic:serve',
npm verb cli   '--verbose' ]
npm info using npm@5.4.0
npm info using node@v6.11.2
npm verb run-script [ 'preionic:serve', 'ionic:serve', 'postionic:serve' ]
npm info lifecycle FFS@0.0.1~preionic:serve: FFS@0.0.1
npm info lifecycle FFS@0.0.1~ionic:serve: FFS@0.0.1

> FFS@0.0.1 ionic:serve E:\Ionic\workspace\mb
> ionic-app-scripts serve

[20:17:19]  ionic-app-scripts 2.1.4
[20:17:19]  watch started ...
[20:17:19]  build dev started ...
[20:17:19]  Proxy added:/ => http://10.100.101.8:8083/
[20:17:19]  clean started ...
[20:17:19]  clean finished in 3 ms
[20:17:19]  copy started ...
[20:17:19]  transpile started ...
[20:17:23]  transpile finished in 4.01 s
[20:17:23]  preprocess started ...
[20:17:23]  deeplinks started ...
[20:17:23]  deeplinks finished in 201 ms
[20:17:23]  preprocess finished in 203 ms
[20:17:23]  webpack started ...
[20:17:24]  copy finished in 4.65 s
E:\Ionic\workspace\mb\node_modules\source-map\lib\source-node.js:115
        node.add(nextLine.substr(0, mapping.generatedColumn));
                         ^

TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (E:\Ionic\workspace\mb\node_modules\source-map\lib\source-node.js:115:26)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (E:\Ionic\workspace\mb\node_modules\source-map\lib\source-map-consumer.js:155:14)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (E:\Ionic\workspace\mb\node_modules\source-map\lib\source-node.js:80
:24)
    at SourceMapSource.node (E:\Ionic\workspace\mb\node_modules\webpack-sources\lib\SourceMapSource.js:39:21)
    at ReplaceSource.node (E:\Ionic\workspace\mb\node_modules\webpack-sources\lib\ReplaceSource.js:70:30)
    at CachedSource.node (E:\Ionic\workspace\mb\node_modules\webpack-sources\lib\CachedSource.js:18:24)
    at E:\Ionic\workspace\mb\node_modules\webpack-sources\lib\ConcatSource.js:37:50
    at Array.map (native)
    at ConcatSource.node (E:\Ionic\workspace\mb\node_modules\webpack-sources\lib\ConcatSource.js:36:63)
npm verb lifecycle FFS@0.0.1~ionic:serve: unsafe-perm in lifecycle true
npm verb lifecycle FFS@0.0.1~ionic:serve: PATH: C:\Users\iaboelsuod\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;E:\Ionic\workspace\mBank
ing\node_modules\.bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\W
indowsPowerShell\v1.0\;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Wind
ows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;F:\Android\SDK\tools;F:\Android\SDK\platform-tools;F:\Android\SDK\tools\bin
;C:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin ;C:\Program Files\nodejs\;C:\Maven\bin;C:\gradle-4.0\bin;C:\Program Files\Java\jdk1.8.0_131\bin
;;C:\Program Files\Microsoft VS Code\bin;C:\Users\iaboelsuod\AppData\Roaming\npm
npm verb lifecycle FFS@0.0.1~ionic:serve: CWD: E:\Ionic\workspace\mb
npm info lifecycle FFS@0.0.1~ionic:serve: Failed to exec ionic:serve script
npm verb stack Error: FFS@0.0.1 ionic:serve: `ionic-app-scripts serve`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Users\iaboelsuod\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:1
6)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Users\iaboelsuod\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:5
5:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:891:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm verb pkgid FFS@0.0.1
npm verb cwd E:\Ionic\workspace\mb
npm verb Windows_NT 10.0.10240
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\iaboelsuod\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ioni
c:serve" "--verbose"
npm verb node v6.11.2
npm verb npm  v5.4.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! FFS@0.0.1 ionic:serve: `ionic-app-scripts serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the FFS@0.0.1 ionic:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\iaboelsuod\AppData\Roaming\npm-cache\_logs\2017-09-05T18_17_31_094Z-debug.log
`

**Comment by wesleymonaro** [comment]
Hi!

Open the file node_modules\source-map\lib\source-node.js and change the lines:

`var nextLine = remainingLines[remainingLinesIndex];`

to

`var nextLine = remainingLines[remainingLinesIndex] || "";`

Run the command:

`npm run ionic:build --verbose` and post here the results ;)

**Comment by ibrahimAboelsuod** [comment]
@wesleymonaro  I already fixed the bug -check "Other information" section. The real issue is the cli not showing an error or anything -at least by default.

**Comment by RanKey1496** [comment]
Hi @ibrahimAboelsuod, can you please tell me how can I fix this? I have the same problema and Idk what to do.
Greetings

**Comment by ibrahimAboelsuod** [comment]
@RanKey1496  Hey ^^,  I think it may happen for a lot of reasons. Do you have the same structure as mine -two components in the same file- ?
If so then you can solve it as mentioned in "Other information" section: 

> you can overcome this issue by embedding the template in the .ts file 

Your English is ok btw ^^

**Comment by pdyraga** [comment]
The same happens if you have two components referencing the same file with `templateUrl`:
```
@Component({
    selector: 'one',
    templateUrl: 'file.html'
})
// ...

@Component({
    selector: 'two',
    templateUrl: 'file.html'
})
// ...
```
The workaround is to include template in the `.ts` with `template` but it leads to HTML code duplication.

Personally, I think having two components referencing the same `.html` file is a perfectly valid scenario. In my case, I render the same view but the behavior is slightly different, depending on which component is used. 

```
$ ionic info

cli packages: (/Users/piotr/git/vanilla/vanilla-mobile/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.2

System:

    Android SDK Tools : 25.2.5
    Node              : v7.10.0
    OS                : OS X El Capitan
    Xcode             : Xcode 8.2.1 Build version 8C1002 
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.8 
    npm               : 4.2.0 
```

```
$ ionic serve -cs --verbose
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: '/Users/piotr/git/vanilla/vanilla-mobile', local: true, binPath:
        '/usr/local/lib/node_modules/ionic/bin/ionic', libPath:
        '/Users/piotr/git/vanilla/vanilla-mobile/node_modules/ionic/dist/index.js' }
[DEBUG] Loading local plugin @ionic/cli-plugin-proxy
[DEBUG] Throwing PLUGIN_NOT_INSTALLED for local @ionic/cli-plugin-proxy
[DEBUG] Loading local plugin @ionic/cli-plugin-cordova
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
[INFO] Starting app-scripts server: --consolelogs --c --serverlogs --s --log-level debug --port 8100 --p 8100
       --livereload-port 35729 --r 35729 --address localhost - Ctrl+C to cancel
[16:20:51]  watch started ... 
[16:20:51]  build dev started ... 
[16:20:51]  Proxy added:/api => http://localhost:8080/api 
[16:20:51]  Proxy added:/static-images => http://localhost:8080/images 
[16:20:51]  clean started ... 
[16:20:51]  clean finished in 1 ms 
[16:20:51]  copy started ... 
[16:20:51]  transpile started ... 
[16:20:54]  transpile finished in 3.13 s 
[16:20:54]  preprocess started ... 
[16:20:54]  deeplinks started ... 
[16:20:54]  deeplinks finished in 68 ms 
[16:20:54]  preprocess finished in 68 ms 
[16:20:54]  webpack started ... 
[16:20:55]  copy finished in 3.42 s 
```
