### ISSUE TITLE
Race condition between `copyFileAsync` and `unlinkAsync` in `source-maps` on NFS

### ISSUE THREAD

**Issue by msbit** [ionic-team/ionic-app-scripts#1227]
#### Short description of the problem:

Running `npm run ionic:build:production` generates source maps as part of the `webpack` step, and then queues up removal as part of `postprocess` (via `purgeSourceMapsIfNeeded` from the `source-maps` module). When running this in an NFS mount (`/Volumes/www/app`), which relaxes a whole bunch of POSIX guarantees, sometimes I have a situation where the `unlinkAsync` occurs before the `copyFileAsync` giving me the error:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Volumes/www/app/www/build/23.js.map'
    at Error (native)
```

or:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Unknown system error -70: Unknown system error -70, open '/Volumes/www/app/www/build/17.js.map'
    at Error (native)
```

The particular file changes depending on which deletion occurs first etc.

#### What behavior are you expecting?

Source-maps to be copied across (if configured) before deletion.

**Steps to reproduce:**
1. Place project on NFS mount
2. Run `npm run ionic:build:production`

**Which @ionic/app-scripts version are you using?**

```
$ grep app-scripts package-lock.json 
    "@ionic/app-scripts": {
      "resolved": "https://registry.npmjs.org/@ionic/app-scripts/-/app-scripts-2.1.4.tgz"
```

**Other information:**

Full output:

```
$ npm run ionic:build:production

> iMediafy@ ionic:build:production /Volumes/www/app
> NODE_ENV=prod ionic-app-scripts build --prod

[14:37:50]  ionic-app-scripts 2.1.4 
[14:37:50]  build prod started ... 
[14:37:50]  clean started ... 
[14:37:50]  clean finished in 97 ms 
[14:37:50]  copy started ... 
[14:37:50]  ngc started ... 
[14:38:38]  ngc finished in 47.42 s 
[14:38:38]  preprocess started ... 
[14:38:38]  deeplinks started ... 
[14:38:43]  deeplinks finished in 4.86 s 
[14:38:43]  optimization started ... 
[14:38:44]  copy finished in 53.48 s 
[14:39:16]  optimization finished in 33.64 s 
[14:39:16]  preprocess finished in 38.51 s 
[14:39:16]  webpack started ... 
[14:40:37]  webpack finished in 81.18 s 
[14:40:37]  sass started ... 
[14:40:37]  uglifyjs started ... 
[14:40:42]  sass finished in 4.77 s 
[14:40:42]  cleancss started ... 
[14:40:44]  cleancss finished in 2.31 s 
[14:42:10]  uglifyjs finished in 92.91 s 
[14:42:10]  postprocess started ... 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Unknown system error -70: Unknown system error -70, open '/Volumes/www/app/www/build/17.js.map'
    at Error (native)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iMediafy@ ionic:build:production: `NODE_ENV=prod ionic-app-scripts build --prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iMediafy@ ionic:build:production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tom/.npm/_logs/2017-09-16T04_42_11_183Z-debug.log
```

`2017-09-16T04_42_11_183Z-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node@6/6.11.2/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'ionic:build:production' ]
2 info using npm@5.4.2
3 info using node@v6.11.2
4 verbose run-script [ 'preionic:build:production',
4 verbose run-script   'ionic:build:production',
4 verbose run-script   'postionic:build:production' ]
5 info lifecycle iMediafy@~preionic:build:production: iMediafy@
6 info lifecycle iMediafy@~ionic:build:production: iMediafy@
7 verbose lifecycle iMediafy@~ionic:build:production: unsafe-perm in lifecycle true
8 verbose lifecycle iMediafy@~ionic:build:production: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Volumes/www/app/node_modules/.bin:/Users/tom/.rbenv/shims:/Users/tom/.rbenv/bin:/Users/tom/google-cloud-sdk/bin:/opt/metasploit-framework/bin:/Users/tom/.luarocks/bin:/Users/tom/Library/Python/2.7/bin:/Users/tom/.composer/vendor/bin:/Users/tom/.cabal/bin:/Users/tom/pear/bin:/Users/tom/bin:/Users/tom/Library/Android/sdk/platform-tools:/Users/tom/Library/Android/sdk/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS
9 verbose lifecycle iMediafy@~ionic:build:production: CWD: /Volumes/www/app
10 silly lifecycle iMediafy@~ionic:build:production: Args: [ '-c', 'NODE_ENV=prod ionic-app-scripts build --prod' ]
11 silly lifecycle iMediafy@~ionic:build:production: Returned: code: 1  signal: null
12 info lifecycle iMediafy@~ionic:build:production: Failed to exec ionic:build:production script
13 verbose stack Error: iMediafy@ ionic:build:production: `NODE_ENV=prod ionic-app-scripts build --prod`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid iMediafy@
15 verbose cwd /Volumes/www/app
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/Cellar/node@6/6.11.2/bin/node" "/usr/local/bin/npm" "run" "ionic:build:production"
18 verbose node v6.11.2
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 1
22 error iMediafy@ ionic:build:production: `NODE_ENV=prod ionic-app-scripts build --prod`
22 error Exit status 1
23 error Failed at the iMediafy@ ionic:build:production script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by msbit** [comment]
As a workaround, I can reliably get through this without error by running:

```
IONIC_GENERATE_SOURCE_MAP=false IONIC_MOVE_SOURCE_MAPS=false npm run ionic:build:production
```

* `IONIC_GENERATE_SOURCE_MAP` to ensure that `shouldPurge` is true inside `copySourcemaps` so `unlinkAsync` does get called
* `IONIC_MOVE_SOURCE_MAPS` to ensure that `copyBeforePurge` is false so `copyFileAsync` doesn't get called

**Comment by danbucholtz** [comment]
Hello,

This should be resolved in `nightly`.

To test, please run:

```
npm install @ionic/app-scripts@3.0.0-201710101530
```

Thanks,
Dan
