### ISSUE TITLE
 [: missing `]' in app-scripts.  Cannot build 3.0.1 app

### ISSUE THREAD

**Issue by JeremyLopez** [ionic-team/ionic-app-scripts#1245]
#### Short description of the problem:
I am attempting to migrate my legacy app to ionic pro and when I try to do my initial push to `ionic master` I get the following error:

```
...
> ionic-app-scripts build

[12:46:11]  ionic-app-scripts 2.1.4 
[12:46:11]  build dev started ... 
[12:46:11]  clean started ... 
[12:46:11]  clean finished in 4 ms 
[12:46:11]  copy started ... 
[12:46:11]  transpile started ... 
[12:46:20]  typescript: node_modules/@angular/compiler/src/aot/static_reflector.d.ts, line: 8 
            Module '"/usr/src/app/node_modules/@angular/core/core"' has no exported member 'ɵReflectorReader'. 

       L8:  export declare class StaticReflector implements ɵReflectorReader {
       L9:      private symbolResolver;

[12:46:20]  typescript: node_modules/@angular/compiler/src/compile_metadata.d.ts, line: 8 
            Module '"/usr/src/app/node_modules/@angular/core/core"' has no exported member 'ɵLifecycleHooks'. 

       L8:  export declare abstract class CompileAnimationStateMetadata {               

[12:46:20]  typescript: node_modules/@angular/compiler/src/directive_resolver.d.ts, line: 8 
            Module '"/usr/src/app/node_modules/@angular/core/core"' has no exported member 'ɵReflectorReader'. 

       L7:   * Return {@link Directive} for a given `Type`.
[12:46:20]  typescript: node_modules/@angular/compiler/src/metadata_resolver.d.ts, line: 8 
       L9:  resolve(type: Type, throwIfNotFound?: boolean): Directive;

            Module '"/usr/src/app/node_modules/@angular/core/core"' has no exported member 'ɵReflectorReader'. 

       L7:  import { NgModuleResolver } from './ng_module_resolver';
       L8:  import { PipeResolver } from './pipe_resolver';                
       L9:  import { ElementSchemaRegistry } from './schema/element_schema_registry';

[12:46:20]  typescript: node_modules/@angular/compiler/src/ng_module_resolver.d.ts, line: 8 
            Module '"/usr/src/app/node_modules/@angular/core/core"' has no exported member 'ɵReflectorReader'. 

       L7:  constructor(_reflector?: ɵReflectorReader);
       L8:  isNgModule(type: any): boolean;      
       L9:  resolve(type: Type, throwIfNotFound?: boolean): NgModule;

            Module '"/usr/src/app/node_modules/@angular/core/core"' has no exported member 'ɵReflectorReader'. 
[12:46:20]  typescript: node_modules/@angular/compiler/src/pipe_resolver.d.ts, line: 8 

       L7:   * See {@link Compiler}
       L9:  export declare class PipeResolver {

[12:46:20]  typescript: node_modules/@angular/compiler/src/template_parser/template_ast.d.ts, line: 8 
            Module '"/usr/src/app/node_modules/@angular/core/core"' has no exported member 'ɵLifecycleHooks'. 

       L8:  export interface TemplateAst {           

[12:46:20]  typescript: node_modules/@angular/platform-browser/animations/src/providers.d.ts, line: 8 
            Module '"/usr/src/app/node_modules/@angular/animations/browser"' has no exported member 
            'ɵDomAnimationEngine'. 

       L8:  export declare function instantiateSupportedAnimationDriver(): NoopAnimationDriver;                   
       L9:  export declare function instantiateDefaultStyleNormalizer(): WebAnimationsStyleNormalizer;

[12:46:20]  ionic-app-script task: "build" 
[12:46:20]  Error: Failed to transpile program 
Error: Failed to transpile program
    at new BuildError (/usr/src/app/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /usr/src/app/node_modules/@ionic/app-scripts/dist/transpile.js:137:20
    at Promise ()
    at transpileWorker (/usr/src/app/node_modules/@ionic/app-scripts/dist/transpile.js:103:12)
    at Object.transpile (/usr/src/app/node_modules/@ionic/app-scripts/dist/transpile.js:61:12)
    at buildProject (/usr/src/app/node_modules/@ionic/app-scripts/dist/build.js:97:78)
    at /usr/src/app/node_modules/@ionic/app-scripts/dist/build.js:47:16
    at 
npm info lifecycle ionic-hello-world@~build: Failed to exec build script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitlab-runner/.npm/_logs/2017-09-27T12_46_20_139Z-debug.log
/snapshot.sh: line 32: [: missing `]'
npm run build failed
Make sure your project has a build script in the package.json
Running after script...
$ clean-up
Cleaning up files...
Successful clean up
ERROR: Job failed: exit status 1
```

**Steps to reproduce:**
1.  link to ionic pro
2. push to ionic

**Which @ionic/app-scripts version are you using?**
```
$ node -v
v6.11.0

$ ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

global packages:

    Cordova CLI : 6.5.0 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.1.2 browser 4.1.0 ios 4.1.1
    Ionic Framework    : ionic-angular 3.0.1

System:

    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    Node       : v6.11.0
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235 
```

**Comment by raihanrazi** [comment]
Is there any update to this? I'm getting the same error.

**Comment by danbucholtz** [comment]
When you run a local build does this happen? ```npm run build -- --prod```

Thanks,
Dan

**Comment by danbucholtz** [comment]
Due to inactivity, we're closing this issue. Please open a new issue if you're still experiencing this issue.

Thanks,
Dan
