### ISSUE TITLE
angularfire2 error on run ionic build --prod

### ISSUE THREAD

**Issue by Midhilaj** [ionic-team/ionic-app-scripts#1253]
I am tying to run ionic build --prod it showing error 

 
 
 

```
Error: ./src/app/child_single_page/child_single_page.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/app/child_single_page'
resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/app/child_single_page'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/app/child_single_page)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/app/child_single_page)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/auth doesn't exist
[/project/ionic/myApp/angularfire2/auth]
[/project/ionic/myApp/angularfire2/auth.js]
[/project/ionic/myApp/angularfire2/auth.ts]
[/project/ionic/myApp/angularfire2/auth]
 @ ./src/app/child_single_page/child_single_page.ngfactory.js 44:0-55
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/app/forgoetpassword/forgoetpassword.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/app/forgoetpassword'
resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/app/forgoetpassword'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/app/forgoetpassword)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/app/forgoetpassword)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/auth doesn't exist
[/project/ionic/myApp/angularfire2/auth]
[/project/ionic/myApp/angularfire2/auth.js]
[/project/ionic/myApp/angularfire2/auth.ts]
[/project/ionic/myApp/angularfire2/auth]
 @ ./src/app/forgoetpassword/forgoetpassword.ngfactory.js 38:0-55
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/app/iteam/item.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/app/iteam'
resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/app/iteam'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/app/iteam)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/app/iteam)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/auth doesn't exist
[/project/ionic/myApp/angularfire2/auth]
[/project/ionic/myApp/angularfire2/auth.js]
[/project/ionic/myApp/angularfire2/auth.ts]
[/project/ionic/myApp/angularfire2/auth]
 @ ./src/app/iteam/item.ngfactory.js 50:0-55
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/app/list_of_items_based_on_category/cat_singlepage.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/app/list_of_items_based_on_category'
resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/app/list_of_items_based_on_category'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/app/list_of_items_based_on_category)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/app/list_of_items_based_on_category)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/auth doesn't exist
[/project/ionic/myApp/angularfire2/auth]
[/project/ionic/myApp/angularfire2/auth.js]
[/project/ionic/myApp/angularfire2/auth.ts]
[/project/ionic/myApp/angularfire2/auth]
 @ ./src/app/list_of_items_based_on_category/cat_singlepage.ngfactory.js 44:0-55
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/app/loginpage/login.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/app/loginpage'
resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/app/loginpage'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/app/loginpage)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/app/loginpage)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/auth doesn't exist
[/project/ionic/myApp/angularfire2/auth]
[/project/ionic/myApp/angularfire2/auth.js]
[/project/ionic/myApp/angularfire2/auth.ts]
[/project/ionic/myApp/angularfire2/auth]
 @ ./src/app/loginpage/login.ngfactory.js 33:0-55
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/app/signup/signup.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/app/signup'
resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/app/signup'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/app/signup)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/app/signup)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/auth doesn't exist
[/project/ionic/myApp/angularfire2/auth]
[/project/ionic/myApp/angularfire2/auth.js]
[/project/ionic/myApp/angularfire2/auth.ts]
[/project/ionic/myApp/angularfire2/auth]
 @ ./src/app/signup/signup.ngfactory.js 38:0-55
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/app/single_page/singlepage.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/app/single_page'
resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/app/single_page'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/app/single_page)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/app/single_page)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/auth doesn't exist
[/project/ionic/myApp/angularfire2/auth]
[/project/ionic/myApp/angularfire2/auth.js]
[/project/ionic/myApp/angularfire2/auth.ts]
[/project/ionic/myApp/angularfire2/auth]
 @ ./src/app/single_page/singlepage.ngfactory.js 36:0-55
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/pages/checkout/checkout.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/pages/checkout'
resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/pages/checkout'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/pages/checkout)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/pages/checkout)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/auth doesn't exist
[/project/ionic/myApp/angularfire2/auth]
[/project/ionic/myApp/angularfire2/auth.js]
[/project/ionic/myApp/angularfire2/auth.ts]
[/project/ionic/myApp/angularfire2/auth]
 @ ./src/pages/checkout/checkout.ngfactory.js 10:0-54
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/pages/home/home.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/pages/home'
resolve '../../../angularfire2/auth' in '/project/ionic/myApp/src/pages/home'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/pages/home)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/pages/home)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/auth doesn't exist
[/project/ionic/myApp/angularfire2/auth]
[/project/ionic/myApp/angularfire2/auth.js]
[/project/ionic/myApp/angularfire2/auth.ts]
[/project/ionic/myApp/angularfire2/auth]
 @ ./src/pages/home/home.ngfactory.js 41:0-55
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/app/child_single_page/child_single_page.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/database' in '/project/ionic/myApp/src/app/child_single_page'
resolve '../../../angularfire2/database' in '/project/ionic/myApp/src/app/child_single_page'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/app/child_single_page)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/app/child_single_page)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/database)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/database doesn't exist
[/project/ionic/myApp/angularfire2/database]
[/project/ionic/myApp/angularfire2/database.js]
[/project/ionic/myApp/angularfire2/database.ts]
[/project/ionic/myApp/angularfire2/database]
 @ ./src/app/child_single_page/child_single_page.ngfactory.js 47:0-59
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/app/iteam/item.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/database' in '/project/ionic/myApp/src/app/iteam'
resolve '../../../angularfire2/database' in '/project/ionic/myApp/src/app/iteam'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/app/iteam)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/app/iteam)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/database)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/database doesn't exist
[/project/ionic/myApp/angularfire2/database]
[/project/ionic/myApp/angularfire2/database.js]
[/project/ionic/myApp/angularfire2/database.ts]
[/project/ionic/myApp/angularfire2/database]
 @ ./src/app/iteam/item.ngfactory.js 53:0-59
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/app/list_of_items_based_on_category/cat_singlepage.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/database' in '/project/ionic/myApp/src/app/list_of_items_based_on_category'
resolve '../../../angularfire2/database' in '/project/ionic/myApp/src/app/list_of_items_based_on_category'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/app/list_of_items_based_on_category)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/app/list_of_items_based_on_category)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/database)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/database doesn't exist
[/project/ionic/myApp/angularfire2/database]
[/project/ionic/myApp/angularfire2/database.js]
[/project/ionic/myApp/angularfire2/database.ts]
[/project/ionic/myApp/angularfire2/database]
 @ ./src/app/list_of_items_based_on_category/cat_singlepage.ngfactory.js 47:0-59
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/app/single_page/singlepage.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/database' in '/project/ionic/myApp/src/app/single_page'
resolve '../../../angularfire2/database' in '/project/ionic/myApp/src/app/single_page'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/app/single_page)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/app/single_page)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/database)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/database doesn't exist
[/project/ionic/myApp/angularfire2/database]
[/project/ionic/myApp/angularfire2/database.js]
[/project/ionic/myApp/angularfire2/database.ts]
[/project/ionic/myApp/angularfire2/database]
 @ ./src/app/single_page/singlepage.ngfactory.js 39:0-59
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/pages/checkout/checkout.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/database' in '/project/ionic/myApp/src/pages/checkout'
resolve '../../../angularfire2/database' in '/project/ionic/myApp/src/pages/checkout'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/pages/checkout)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/pages/checkout)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/database)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/database doesn't exist
[/project/ionic/myApp/angularfire2/database]
[/project/ionic/myApp/angularfire2/database.js]
[/project/ionic/myApp/angularfire2/database.ts]
[/project/ionic/myApp/angularfire2/database]
 @ ./src/pages/checkout/checkout.ngfactory.js 11:0-58
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/pages/home/home.ngfactory.js
Module not found: Error: Can't resolve '../../../angularfire2/database' in '/project/ionic/myApp/src/pages/home'
resolve '../../../angularfire2/database' in '/project/ionic/myApp/src/pages/home'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/pages/home)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/pages/home)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/database)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/database doesn't exist
[/project/ionic/myApp/angularfire2/database]
[/project/ionic/myApp/angularfire2/database.js]
[/project/ionic/myApp/angularfire2/database.ts]
[/project/ionic/myApp/angularfire2/database]
 @ ./src/pages/home/home.ngfactory.js 42:0-59
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/app/app.component.ngfactory.js
Module not found: Error: Can't resolve '../../angularfire2/auth' in '/project/ionic/myApp/src/app'
resolve '../../angularfire2/auth' in '/project/ionic/myApp/src/app'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/app)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/auth doesn't exist
[/project/ionic/myApp/angularfire2/auth]
[/project/ionic/myApp/angularfire2/auth.js]
[/project/ionic/myApp/angularfire2/auth.ts]
[/project/ionic/myApp/angularfire2/auth]
 @ ./src/app/app.component.ngfactory.js 41:0-52
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '../../angularfire2/auth' in '/project/ionic/myApp/src/app'
resolve '../../angularfire2/auth' in '/project/ionic/myApp/src/app'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/app)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/auth.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/auth doesn't exist
[/project/ionic/myApp/angularfire2/auth]
[/project/ionic/myApp/angularfire2/auth.js]
[/project/ionic/myApp/angularfire2/auth.ts]
[/project/ionic/myApp/angularfire2/auth]
 @ ./src/app/app.module.ngfactory.js 52:0-52
 @ ./src/app/main.ts,./src/app/app.component.ngfactory.js
Module not found: Error: Can't resolve '../../angularfire2/database' in '/project/ionic/myApp/src/app'
resolve '../../angularfire2/database' in '/project/ionic/myApp/src/app'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/app)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/database)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/database doesn't exist
[/project/ionic/myApp/angularfire2/database]
[/project/ionic/myApp/angularfire2/database.js]
[/project/ionic/myApp/angularfire2/database.ts]
[/project/ionic/myApp/angularfire2/database]
 @ ./src/app/app.component.ngfactory.js 43:0-56
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '../../angularfire2/database' in '/project/ionic/myApp/src/app'
resolve '../../angularfire2/database' in '/project/ionic/myApp/src/app'
  using description file: /project/ionic/myApp/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /project/ionic/myApp/package.json (relative path: ./src/app)
    using description file: /project/ionic/myApp/package.json (relative path: ./angularfire2/database)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /project/ionic/myApp/angularfire2/database.ts doesn't exist
      as directory
        /project/ionic/myApp/angularfire2/database doesn't exist
[/project/ionic/myApp/angularfire2/database]
[/project/ionic/myApp/angularfire2/database.js]
[/project/ionic/myApp/angularfire2/database.ts]
[/project/ionic/myApp/angularfire2/database]
 @ ./src/app/app.module.ngfactory.js 32:0-56
 @ ./src/app/main.ts
    at new BuildError (/project/ionic/myApp/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /project/ionic/myApp/node_modules/@ionic/app-scripts/dist/preprocess.js:18:21
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Which @ionic/app-scripts version are you using?**
CLI 3.12.0

**Comment by danbucholtz** [comment]
Hello,

Please fill out the issue template and provide a minimal example using `ionic start myIssueSample blank`. I'll take a look then.

Thanks,
Dan

**Comment by danbucholtz** [comment]
Due to lack of response, we're closing the issue. Feel free to create another one with the issue template properly filled out.

Thanks,
Dan
