### ISSUE TITLE
OutOfMemory error using file plugin

### ISSUE THREAD

**Issue by AramVave** [ionic-team/ionic-app-scripts#1275]
I am using the file plugin and I randomly get this error on Android:

E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
Process: ********, PID: 31862
java.lang.OutOfMemoryError: Failed to allocate a 22959965 byte allocation with 15635568 free bytes and 14MB until OOM
at android.util.Base64.decode(Base64.java:171)
at android.util.Base64.decode(Base64.java:136)
at android.util.Base64.decode(Base64.java:118)
at org.apache.cordova.file.LocalFilesystem.writeToFileAtURL(LocalFilesystem.java:387)
at org.apache.cordova.file.FileUtils.write(FileUtils.java:1137)
at org.apache.cordova.file.FileUtils$9.run(FileUtils.java:364)
at org.apache.cordova.file.FileUtils$25.run(FileUtils.java:663)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)

Some people suggested using android:largeHeap="true" in manifest. Is there a way to fix this using the plugin?

**Comment by hitendramalviya** [comment]
Did you get any resolution for this error, I am also getting similar error while capturing image from camera?
