### ISSUE TITLE
Error when serving offline

### ISSUE THREAD

**Issue by moldstadt** [ionic-team/ionic-app-scripts#1287]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
When working offline I get the following errors when trying to do network requests to local WAMP server:
```
Error: getaddrinfo ENOENT localhost:80
    at Object._errnoException (util.js:1022:11)
    at errnoException (dns.js:58:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
```

I am using a proxy to connect to localhost.

I don't get these errors if I connect to the Internet.

#### What behavior are you expecting?
No errors when offline.

**Steps to reproduce:**
1. ionic serve
2. do a network request
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
```
$ ionic info
cli packages: (C:\Users\Brent.SST\AppData\Roaming\npm\node_modules)
    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.2
global packages:
    cordova (Cordova CLI) : 7.0.1
local packages:
    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.7.1
System:
    Android SDK Tools : 26.0.2
    Node              : v8.3.0
    npm               : 5.3.0
    OS                : Windows 8.1
Misc:
    backend : legacy
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by romain10009** [comment]
I have the same issue, there was talk about this [here]( https://github.com/ionic-team/ionic-cli/issues/2397)
