### ISSUE TITLE
Close chrome browser stop ionic serve

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-app-scripts#1344]
#### Short description of the problem:

After my upgrade to nodejs 9.3.0 (from 8) I noticed that closing the chrome browser window (in incognito mode), where I debug my app, often lead to stopping the ionic local server

#### What behavior are you expecting?

`ionic serve` should not be stopped when I close a browser window

**Steps to reproduce:**
1. ionic serve
2. open a chrome new window/tab in incognito mode
3. debug your app
4. close the chrome window

**Log**

> [17:47:51]  sass finished in 1.92 s 
> [17:47:51]  postprocess started ... 
> [17:47:51]  postprocess finished in 235 ms 
> [17:47:51]  lint started ... 
> [17:47:51]  build dev finished in 30.50 s 
> [17:47:51]  watch ready in 30.75 s 
> [17:47:51]  dev server running: http://localhost:8100/ 
>
> [OK] Development server running!
>
>      Local: http://localhost:8100
>      External: http://192.168.43.103:8100, http://169.254.143.79:8100
>      DevApp: myapp@8100 on MyMacbook
> 
> [17:48:01]  lint finished in 9.88 s 
> events.js:136
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: read ECONNRESET
>     at _errnoException (util.js:999:13)
>     at TCP.onread (net.js:629:25)

**Ionic info**

cli packages:

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 5.0.13 
    Node              : v9.3.0
    npm               : 5.6.0 
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /...

Misc:

    backend : pro

**Comment by peterpeterparker** [comment]
This issue looks like a duplicate of https://github.com/ionic-team/ionic-cli/issues/2921
