### ISSUE TITLE
`ionic serve` stops after "build dev started"

### ISSUE THREAD

**Issue by coloz** [ionic-team/ionic-app-scripts#1356]
#### Short description of the problem:
using 3.1.6 and 3.1.7 ,`ionic serve` stops after "build dev started",but 3.1.2 is all right

**error info:**
PS C:\Users\coloz\Desktop\image2bitmap> npm run ionic:serve

> image2bitmap@0.0.1 ionic:serve C:\Users\coloz\Desktop\image2bitmap
> ionic-app-scripts serve

[15:03:19]  ionic-app-scripts 3.1.6
[15:03:19]  watch started ...
[15:03:19]  build dev started ...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::53703
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at new WebSocketServer (C:\Users\coloz\Desktop\image2bitmap\node_modules\ws\lib\WebSocketServer.js:77:20)
    at Object.createNotificationServer (C:\Users\coloz\Desktop\image2bitmap\node_modules\@ionic\app-scripts\dist\dev-server\notification-server.js:66:15)
    at C:\Users\coloz\Desktop\image2bitmap\node_modules\@ionic\app-scripts\dist\serve.js:47:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! image2bitmap@0.0.1 ionic:serve: `ionic-app-scripts serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the image2bitmap@0.0.1 ionic:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\coloz\AppData\Roaming\npm-cache\_logs\2018-01-01T07_03_19_313Z-debug.log

**Comment by rayhaanq** [comment]
similar issue on 3.19.0

**Comment by JoeyHengst** [comment]
@coloz looks like your port 53703 is already in use. Start from a clean start and try again.
