### ISSUE TITLE
`$ ionic build --prod` failure

### ISSUE THREAD

**Issue by rafbgarcia** [ionic-team/ionic-app-scripts#1381]
#### Short description of the problem:

Trying to run that command and it fails with this error:

```
Can't resolve all parameters for MyApp in /Users/rafa/natal-food/imoto-motoboys/src/app/app.component.ts:
            ([object Object], [object Object], [object Object], ?).
```

See:

```
➜  imoto-motoboys git:(master) ✗ ionic build --prod
Running app-scripts build: --prod
[01:34:30]  build prod started ...
[01:34:30]  clean started ...
[01:34:30]  clean finished in 2 ms
[01:34:30]  copy started ...
[01:34:30]  deeplinks started ...
[01:34:30]  deeplinks finished in 58 ms
[01:34:30]  ngc started ...
[01:34:34]  typescript error
            Can't resolve all parameters for MyApp in /Users/rafa/natal-food/imoto-motoboys/src/app/app.component.ts:
            ([object Object], [object Object], [object Object], ?).

Error: The Angular AoT build failed. See the issues above
    at /Users/rafa/natal-food/imoto-motoboys/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:237:55
    at step (/Users/rafa/natal-food/imoto-motoboys/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/Users/rafa/natal-food/imoto-motoboys/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/Users/rafa/natal-food/imoto-motoboys/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
    at <anonymous>
[01:34:34]  copy finished in 3.44 s
```

But I have my provider normally setup on `app.module.ts`.

#### Relevant code

```ts
# app.component.ts

import { Component, ViewChild } from '@angular/core'
import { Nav, Platform } from 'ionic-angular'
import { StatusBar } from '@ionic-native/status-bar'
import { SplashScreen } from '@ionic-native/splash-screen'

import HomePage from '../pages/home/home'
import LoginPage from '../pages/login/login'
import Motoboy from '../services/motoboy'

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  @ViewChild(Nav) nav: Nav

  rootPage: any

  pages: Array<{title: string, component: any}>

  constructor(
    public platform: Platform,
    public statusBar: StatusBar,
    public splashScreen: SplashScreen,
    public motoboy: Motoboy,
  ) {}
```

```ts
# app.module.ts

import Motoboy from '../services/motoboy'
...
  providers: [
    Motoboy,
```

**Which @ionic/app-scripts version are you using?**

3.1.8

Does anyone have a clue how to proceed here? Spent the entire day trying to figure out how to fix that 😞

**Comment by rafbgarcia** [comment]
I managed to get this to work, it's very difficult to address this issue due to the really bad error message it throws.

For more info, see my answer here:
https://forum.ionicframework.com/t/issue-running-ionic-build-prod/120435/16


### Copy/paste 

Apparently I can't `export default class`, this was the entire ******* issue.

My steps:

### Step 1

Create a new ionic project and make check whether `$ ionic build --prod` works.

It did work.

### Step 2

Try to make the build fail.

I achieved that creating a service and trying to use it in `app.component.ts`

```
import { Injectable } from '@angular/core'

@Injectable()
export default class Service {
  constructor() {}
}
```

### Step 3

Try to make the build pass.

Updated my service to do an `export class Service` instead of `export default class Service`

```
import { Injectable } from '@angular/core'

@Injectable()
export class Service {
  constructor() {}
}
```

It passed.

## Conclusion

Both errors were solved by that.

1- `app.component.ts` -> `Can't resolve all parameters for MyApp [...]`
2- `app.module.ts` -> `Unexpected value 'null' declared by the module 'AppModule in [...]`
