### ISSUE TITLE
The error message from `build` command does not contain details when `ngc` fails

### ISSUE THREAD

**Issue by smt116** [ionic-team/ionic-app-scripts#1401]
## Short description of the problem:

When the TypeScript is configured with `noEmitOnError` and `strictNullChecks`, the build for production fails without any details.

Note that it doesn't fail for development and while linting the project.

## What behavior are you expecting?

I would like to see the output from the `ngc` with details why it had failed.

Also, it would be also great to see these errors from `ngc` while building for development.

## Steps to reproduce

1. Install `ionic` version 3.19.1
1. Run `ionic start`
1. Provide any name for the sample project
1. Pick `blank` option
1. Skip Cordova integration and Pro SDK installation
1. Go to the project's directory and install dependencies (I've used `yarn`)
1. Set `strictNullChecks` and `noEmitOnError` TypeScript's configuration options:

    ```diff
    diff --git a/tsconfig.json b/tsconfig.json
    index 5d53142..72c27fb 100644
    --- a/tsconfig.json
    +++ b/tsconfig.json
    @@ -11,7 +11,9 @@
        "module": "es2015",
        "moduleResolution": "node",
        "sourceMap": true,
    -    "target": "es5"
    +    "target": "es5",
    +    "noEmitOnError": true,
    +    "strictNullChecks": true
      },
      "include": [
        "src/**/*.ts"
    ```

1. Build the project for production and note the error message without details (I'm using yarn but you can reproduce it with npm as well):

    ```bash
    ts-test λ yarn run ionic-app-scripts build --prod
    yarn run v1.3.2
    $ /Users/smefju/tmp/ts-test/node_modules/.bin/ionic-app-scripts build --prod
    [09:31:17]  ionic-app-scripts 3.1.8
    [09:31:17]  build prod started ...
    [09:31:17]  clean started ...
    [09:31:17]  clean finished in 2 ms
    [09:31:17]  copy started ...
    [09:31:17]  deeplinks started ...
    [09:31:17]  deeplinks finished in 32 ms
    [09:31:17]  ngc started ...
    [09:31:23]  ionic-app-script task: "build"
    [09:31:23]  Error: Could not find entry point (bootstrap file) /Users/smefju/tmp/ts-test/src/app/main.ts
    Error: Could not find entry point (bootstrap file) /Users/smefju/tmp/ts-test/src/app/main.ts
        at replaceBootstrap (/Users/smefju/tmp/ts-test/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:125:39)
        at Object.<anonymous> (/Users/smefju/tmp/ts-test/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:92:48)
        at step (/Users/smefju/tmp/ts-test/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
        at Object.next (/Users/smefju/tmp/ts-test/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
        at fulfilled (/Users/smefju/tmp/ts-test/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
        at <anonymous>
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    ```
1. Note that `yarn run ionic-app-scripts build` and `yarn run ionic-app-scripts lint` works fine.

## Software versions

1. `ionic --version`: 3.19.1
1. `tsc --version`: 2.4.2
1. `tslint --version`: 5.4.3
1. `package.json` (default after generating a sample project):

    ```json
    {
      "name": "ts-test",
      "version": "0.0.1",
      "author": "Ionic Framework",
      "homepage": "http://ionicframework.com/",
      "private": true,
      "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
      },
      "dependencies": {
        "@angular/common": "5.0.3",
        "@angular/compiler": "5.0.3",
        "@angular/compiler-cli": "5.0.3",
        "@angular/core": "5.0.3",
        "@angular/forms": "5.0.3",
        "@angular/http": "5.0.3",
        "@angular/platform-browser": "5.0.3",
        "@angular/platform-browser-dynamic": "5.0.3",
        "@ionic-native/core": "4.4.0",
        "@ionic-native/splash-screen": "4.4.0",
        "@ionic-native/status-bar": "4.4.0",
        "@ionic/storage": "2.1.3",
        "ionic-angular": "3.9.2",
        "ionicons": "3.0.0",
        "rxjs": "5.5.2",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.18"
      },
      "devDependencies": {
        "@ionic/app-scripts": "3.1.8",
        "typescript": "2.4.2"
      },
      "description": "An Ionic project"
    }
    ```
1. `tsconfig.json` (with added flags):

    ```json
    {
      "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "declaration": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "lib": [
          "dom",
          "es2015"
        ],
        "module": "es2015",
        "moduleResolution": "node",
        "sourceMap": true,
        "target": "es5",
        "noEmitOnError": true,
        "strictNullChecks": true
      },
      "include": [
        "src/**/*.ts"
      ],
      "exclude": [
        "node_modules",
        "src/**/*.spec.ts",
        "src/**/__tests__/*.ts"
      ],
      "compileOnSave": false,
      "atom": {
        "rewriteTsconfig": false
      }
    }
    ```

1. `tslint.json` (default after generating a sample project):

    ```json
    {
      "rules": {
        "no-duplicate-variable": true,
        "no-unused-variable": [
          true
        ]
      },
      "rulesDirectory": [
        "node_modules/tslint-eslint-rules/dist/rules"
      ]
    }
    ```

## Other information:

You can see actual error messages that made `build` failed by running `ngc` manually:

```bash
yarn run ngc -p tsconfig.json
yarn run v1.3.2
$ /Users/smefju/tmp/ts-test/node_modules/.bin/ngc -p tsconfig.json
Error at /Users/smefju/tmp/ts-test/node_modules/ionic-angular/components/alert/alert-component.d.ts.AlertCmp.html(1,417): Object is possibly 'undefined'.
Error at /Users/smefju/tmp/ts-test/node_modules/ionic-angular/components/alert/alert-component.d.ts.AlertCmp.html(1,1760): Object is possibly 'undefined'.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This error exists because of the broken `ionic-angular` package (the newest 3.9.2 version). It contains [a bug that breaks `strictNullChecks`](https://github.com/ionic-team/ionic/issues/14056) (https://github.com/ionic-team/ionic/issues/14056). There is [a pull request with the fix](https://github.com/ionic-team/ionic/pull/14057) (https://github.com/ionic-team/ionic/pull/14057).

**Comment by sebbico** [comment]
have you fixed this error? I have the same problem
