### ISSUE TITLE
Error: Missing binding

### ISSUE THREAD

**Issue by HeDongXinRoad** [ionic-team/ionic-app-scripts#1423]
rror: Missing binding D:\cmb_project\newAPP\node_modules\node-sass\vendor\wi
n32-x64-57\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit
with Node.js 8.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm ins
tall`.
Run `npm rebuild node-sass --force` to build the binding for your current enviro
nment.
    at module.exports (D:\cmb_project\newAPP\node_modules\node-sass\lib\bindi
ng.js:15:13)
    at Object.<anonymous> (D:\cmb_project\newAPP\node_modules\node-sass\lib\i
ndex.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\cmb_project\newAPP\node_modules\@ionic\app-scri
pts\dist\core\bundle-components.js:6:16)

**Comment by davidquon** [comment]
@HeDongXinRoad Did you ever find a solution to this?  I seem to be seeing a similar issue.

I'm trying to upgrade my Ionic but am blocked by this.  Here's my `ionic info`:
```
$ ionic info

Ionic:

   ionic (Ionic CLI)  : 4.9.0 (/Users/DQ/.nvm/versions/node/v10.15.0/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.1, (and 3 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/DQ/Library/Android/sdk)
   NodeJS            : v10.15.0 (/Users/DQ/.nvm/versions/node/v10.15.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Sierra
   Xcode             : Xcode 9.2 Build version 9C40b
```
I've tried all variations `npm rebuild node-sass`, nuking `node_modules` and `npm install`, etc.  It seems that the correct version of `node-sass` exists in `vendor/darwin-x64-64` however for some reason it keeps looking for `vendor/darwin-x64-57`.  😞

**Comment by davidquon** [comment]
I knew this would happen.  Post something then find the fix.  🎉  Turns out this problem is with VS Code IDE and NVM.  Seems that VS Code is tied the the default NVM version for certain things like `Run android on device` for some reason.  Changing the default NVM version fixed this for me.  This explains why it would run from the terminal but not in VS Code with the same command.
https://stackoverflow.com/questions/44700432/visual-studio-code-to-use-node-version-specified-by-nvm
