### ISSUE TITLE
Runtime Error: process.binding is not supported

### ISSUE THREAD

**Issue by kpj16** [ionic-team/ionic-app-scripts#1445]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?
App should be running on browser.

**Steps to reproduce:**
1. Create application: ionic start <app_name> tabs
2. cd to <app_name> directory
3. npm install --save ssh2
4. open project, go to any page (e.g. home.ts) and import ssh2 from 'ssh2';
5. Inside constructor type: console.dir(ssh2); Run ionic serve
6. Get Error: Cannot find module: dns
7. Added dns config as per https://github.com/ionic-team/ionic-app-scripts/issues/956
Adding  dns: 'empty' to @ionic/app-scripts/config/webpack.config.js
8. Run application again and get Error: process.binding is not supported

**Which @ionic/app-scripts version are you using?**
Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.10
Angular Core: 5.2.11
Angular Compiler CLI: 5.2.11
Node: 8.11.2
OS Platform: Windows 10

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Stack:
Error: process.binding is not supported
    at Object.process.binding (http://localhost:8100/build/vendor.js:28354:11)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:151715:62)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:154680:30)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.module.exports.newInvalidAsn1Error (http://localhost:8100/build/vendor.js:72887:15)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:140649:20)
    at Object.exports.byteLength (http://localhost:8100/build/vendor.js:142191:30)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.244 (http://localhost:8100/build/main.js:154:63)

https://github.com/ionic-team/ionic-app-scripts/issues/956
https://github.com/mscdex/ssh2

**Comment by kpj16** [comment]
Answered through: https://stackoverflow.com/questions/42799888/can-you-use-the-node-package-ssh2-in-a-browser
