### ISSUE TITLE
Generate APK file

### ISSUE THREAD

**Issue by AmineSkills** [ionic-team/ionic-app-scripts#1480]
Hi, can you tell why my app can't generate the **apk file** !? thank you in advance.

I added these lines to **package.json** :

    "build:development:ios": "ionic cordova build ios",
    "build:development:android": "ionic cordova build android",
    "build:production:ios": "ionic cordova build ios --prod --release",
    "build:production:android": "ionic cordova build android --prod --release"

When i execute this command "npm run build:development:android" by CLI: it displays these errors:
 
_You have been opted out of telemetry. To change this, run: cordova telemetry on.
Android Studio project detected
(node:34354) UnhandledPromiseRejectionWarning: CordovaError: Failed to find 'JAVA_HOME' environment variable. Try setting it manually.
    at /Users/mac/Desktop/projets/cielapp/platforms/android/cordova/lib/check_reqs.js:177:35
    at _rejected (/Users/mac/Desktop/projets/cielapp/platforms/android/cordova/node_modules/q/q.js:864:24)
    at /Users/mac/Desktop/projets/cielapp/platforms/android/cordova/node_modules/q/q.js:890:30
    at Promise.when (/Users/mac/Desktop/projets/cielapp/platforms/android/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/Users/mac/Desktop/projets/cielapp/platforms/android/cordova/node_modules/q/q.js:808:41)
    at /Users/mac/Desktop/projets/cielapp/platforms/android/cordova/node_modules/q/q.js:624:44
    at runSingle (/Users/mac/Desktop/projets/cielapp/platforms/android/cordova/node_modules/q/q.js:137:13)
    at flush (/Users/mac/Desktop/projets/cielapp/platforms/android/cordova/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:34354) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:34354) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code._

**Comment by AmineSkills** [comment]
Hi, i resolved the problem (this for MacOs of course) :

First of all, this command was very important for me, 
`cordova requirements`

Steps:
1. I deactivated telemetry : 
`cordova telemetry off`

2. I downloaded and installed JDK version 8 : 
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html 

N.B: maybe you can find a version problem if you do not install this version, so anyway you can try to delete the wrong version if it does not work ! For example, i installed the 10 version but it displays error in building, so i deleted it by this:
`sudo rm -rf jdk-10.0.2.jdk`

3. I uploaded **Gradle** :
https://gradle.org/install/#manually

N.B: I uploaded the complete version.

4. I putted the Gradle folder in the folder of my project (i think this is optional to choose the path !)
 
5. Return to user folder : 
`cd ~/`

6. Create a file called **.bash_profile** in user folder 
`touch .bash_profile`

7. Open this file
`open -e .bash_profile`

8. I wrote the content below in this file :

**
> export JAVA_HOME=${/usr/libexec/java_home}
> export GRADLE_HOME=/Users/mac/Desktop/Projets/gradle-4.10.1
> export PATH=$PATH:$GRADLE_HOME/bin
**

N.B: you can see that i putted the Gradle folder (pay attention to the version that you will upload) in "Desktop/Projets".

9. i executed this command to install Gradle :
`gradle `
