### ISSUE TITLE
Error building Ionic 2 app with --prod flag (Cannot read property 'map' of undefined)

### ISSUE THREAD

**Issue by pharos42** [ionic-team/ionic-app-scripts#976]
#### Short description of the problem:
When I build my Ionic2 application with --prod flag I get the error:

[14:56:45]  ionic-app-script task: "build"
[14:56:45]  TypeError: Cannot read property 'map' of undefined

#### What behavior are you expecting?
failure either indicates what in the project is incorrect, if anything, or builds successfully.

**Steps to reproduce:**
1. run command ionic build android --prod --release

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
ionic-app-scripts 1.3.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
TypeError: Cannot read property 'map' of undefined
    at Evaluator.evaluateNode (C:\code\nsc\surecheckportal\node_modules\@angular\tsc-wrapped\src\evaluator.js:304:54)
    at classMetadataOf (C:\code\nsc\surecheckportal\node_modules\@angular\tsc-wrapped\src\collector.js:197:59)
    at C:\code\nsc\surecheckportal\node_modules\@angular\tsc-wrapped\src\collector.js:324:72
    at visitEachNode (C:\code\nsc\surecheckportal\node_modules\typescript\lib\typescript.js:14209:30)
    at Object.forEachChild (C:\code\nsc\surecheckportal\node_modules\typescript\lib\typescript.js:14382:24)
    at MetadataCollector.getMetadata (C:\code\nsc\surecheckportal\node_modules\@angular\tsc-wrapped\src\collector.js:280:12)
    at CompilerHost.getMetadataFor (C:\code\nsc\surecheckportal\node_modules\@angular\compiler-cli\src\compiler_host.js:185:51)
    at StaticSymbolResolver.getModuleMetadata (C:\code\nsc\surecheckportal\node_modules\@angular\compiler\bundles\compiler.umd.js:23870:62)
    at StaticSymbolResolver._createSymbolsOf (C:\code\nsc\surecheckportal\node_modules\@angular\compiler\bundles\compiler.umd.js:23685:46)
    at StaticSymbolResolver.getSymbolsOf (C:\code\nsc\surecheckportal\node_modules\@angular\compiler\bundles\compiler.umd.js:23666:14)

**Comment by danbucholtz** [comment]
Please try `@ionic/app-scripts@latest`.

Thanks,
Dan

**Comment by pharos42** [comment]
I believe I have determined that this error occurs if you have somewhere in your code `new xxx` without the trailing ();  It also occurs if you have `new class extends blah {}` unless you include a () after the closing curly bracket.
I tested with @latest which appears to be 1.3.7.  The problem still occurs.
Unfortunately after cleaning up all the instances of new that don't have parenthesis i was still broken by another issue I am investigating (which looks like it may already be a reported issue): 
Error: Type FileSelectDirective in
            C:/code/nsc/surecheckportal/node_modules/ng2-file-upload/file-upload/file-select.directive.d.ts is part of 2 modules: FileUploadModule in
            C:/code/nsc/surecheckportal/node_modules/ng2-file-upload/file-upload/file-upload.module.d.ts and
            PlatformModule in C:/code/nsc/surecheckportal/src/pages/platform/platform.module.ts! Please consider moving

**Comment by jgw96** [comment]
Hello @pharos42 , could you post an example of the code snippet that causes the issue?

**Comment by pharos42** [comment]
I'll get back to you if i can make a small example project.  This particular problem went away when i searched for and replaced all instances of using 'new' to construct an object that was missing "()", which is optional per the language specification.
I suppose you should be able to replicate it by something as simple as:
`let test = new String;`

**Comment by fleshka779** [comment]
ionic cordova run android  --prod --release
```
[12:44:27]  preprocess finished in 33.45 s 
[12:44:27]  webpack started ... 
[12:46:39]  webpack finished in 131.72 s 
[12:46:39]  sass started ... 
[12:46:39]  uglifyjs started ... 
Error: ENOENT: no such file or directory, open '/Users/mac/Desktop/Test/www/build/main.js.map' in undefined at line undefined, col undefined, pos undefined

Segmentation fault: 11
```

**package.json**
```
"@angular/common": "4.1.0",
    "@angular/compiler": "4.1.0",
    "@angular/compiler-cli": "4.1.0",
    "@angular/core": "4.1.0",
    "@angular/forms": "4.1.0",
    "@angular/http": "4.1.0",
    "@angular/platform-browser": "4.1.0",
    "@angular/platform-browser-dynamic": "4.1.0",`
```
**devDependencies**
`"@ionic/app-scripts": "^1.3.7"`

```
"config": {
    "ionic_bundler": "webpack",
    "ionic_generate_source_map": true,
    "ionic_source_map_type": "source-map"
  }
```

**Comment by danbucholtz** [comment]
Please provide a minimal repository showing us how we can recreate this. Is it possible that you're not transpiling to ES5 and that is making uglify error out? Unfortunately, I don't think this is a common issue to app-scripts. With that in mind I am going to close this issue. Once we can isolate it in a minimal example, I'll re-open and resolve.

Thanks,
Dan
